import json
import uuid
from pathlib import Path


def cell_id():
    return uuid.uuid4().hex[:12]


def lines(*args):
    '''Join args with newlines, return as list of 'line\n' strings.'''
    result = []
    for a in args:
        for ln in str(a).split('\n'):
            result.append(ln + '\n')
    if result:
        result[-1] = result[-1].rstrip('\n')
    return result


def md(*parts, cid=None):
    return {'cell_type': 'markdown', 'id': cid or cell_id(), 'metadata': {}, 'source': lines(*parts)}


def code(*parts, cid=None):
    return {
        'cell_type': 'code',
        'id': cid or cell_id(),
        'metadata': {},
        'execution_count': None,
        'outputs': [],
        'source': lines(*parts),
    }


def lesson(label, title, *body):
    return code(f'# 💻 {label}  {title}', '# ─────────────────────────────────────────────────────────────────────────────', *body)


def exmd(num, title, task, steps, hint):
    step_lines = [f'{i}. {step}' for i, step in enumerate(steps, start=1)]
    return md(
        f'### 🎯 Exercise {num} — {title}',
        '',
        f'**Task:** {task}',
        '',
        '**Steps:**',
        *step_lines,
        '',
        '**Hint:**',
        '',
        '```python',
        hint,
        '```',
    )


def exstub(num, comments):
    body = [f'# {i}. {comment}' for i, comment in enumerate(comments, start=1)]
    return code(f'# 🎯 Exercise {num} — your code here ────────────────────────────────', *body)


def exsol(num, *body):
    return code(f'# ✅ Exercise {num} — Solution ──────────────────────────────────────', *body)


def labstep(num, title, *body):
    return code(f'# 🔬 Step {num} — {title}', '# ─────────────────────────────────────────────────────────────────────────────', *body)


REPO_ROOT = Path(__file__).resolve().parents[3]
OUT = REPO_ROOT / 'notebooks' / 'geospatial_python_course' / 'week_06_postgresql_data_loading.ipynb'
OUT.parent.mkdir(parents=True, exist_ok=True)

metadata = {
    'kernelspec': {
        'display_name': 'Python 3 (ipykernel)',
        'language': 'python',
        'name': 'python3',
    },
    'language_info': {
        'codemirror_mode': {'name': 'ipython', 'version': 3},
        'file_extension': '.py',
        'mimetype': 'text/x-python',
        'name': 'python',
        'pygments_lexer': 'ipython3',
        'version': '3.11.0',
    },
    'toc-autonumbering': False,
}

section_topics = [
    ('1 — Why PostgreSQL for Geospatial Data', 'SQLite, PostgreSQL, and PostGIS roles'),
    ('2 — Direct DBAPI with psycopg2', 'connect(), cursor(), and parameterized queries'),
    ('3 — SQLAlchemy Core', 'Table metadata, inserts, and portable SQL'),
    ('4 — Schema Design for Geospatial Records', 'Columns, validation, and geometry storage'),
    ('5 — Creating Tables and Indexes', 'DDL, inspector, BTREE, and GIST concepts'),
    ('6 — Inserting Data', 'Bulk inserts, row-by-row fallback, and logging'),
    ('7 — Transaction Management', 'ACID, rollback, and savepoints'),
    ('8 — Querying Data', 'SELECT, aggregation, and DataFrame conversion'),
    ('9 — PostGIS Setup and Spatial Columns', 'Extension setup, SRID, and WKT round-trip'),
    ('10 — Spatial ETL Module', 'Validation, load, verify, and reporting'),
]
toc_rows = '\n'.join(f'| [{left}](#section-{i}) | {right} |' for i, (left, right) in enumerate(section_topics, start=1))
symbol_rows = '\n'.join([
    '| Symbol | Meaning |',
    '|--------|---------|',
    '| 💻 | Runnable code cell |',
    '| 🎯 | Exercise — write your own code |',
    '| ✅ | Solution — run after attempting |',
    '| 🔬 | Mini-Lab step |',
    '| 📖 | Explanatory section |',
    '| 💡 | Tip or best practice |',
    '| ⚠️ | Common mistake or warning |',
    '| 🐘 | PostgreSQL-specific (requires live server) |',
])

week_title = md(
    '# 🌍 Week 6 — PostgreSQL Connection & Data Loading',
    '### Geospatial Python Mastery | Module 4: Spatial Databases',
    '',
    '---',
    '',
    '|  |  |',
    '|---|---|',
    '| **Course** | Geospatial Python Mastery |',
    '| **Week** | 6 of 10 |',
    '| **Theme** | PostgreSQL Connection & Data Loading |',
    '| **Duration** | 3 hours |',
    '| **Level** | Intermediate |',
    '| **Module** | Module 4: Spatial Databases |',
    '| **Practice Outcome** | Build a reusable spatial ETL workflow that can target SQLite today and PostgreSQL/PostGIS later |',
    '',
    '---',
    '',
    '> 🗺️ **Why this week matters**',
    '> Spatial analysis projects quickly outgrow single files. This week you will connect Python to a database,',
    '> design schemas for longitude and latitude data, load records safely, and prepare for true PostGIS tables.',
    '> The runnable examples use SQLite so the notebook works everywhere, while every important step is mapped',
    '> to the PostgreSQL and PostGIS patterns you will use in production.',
    '',
    '---',
    '',
    '## 📋 Table of Contents',
    '',
    '| Section | Topic |',
    '|---------|-------|',
    toc_rows,
    '',
    '---',
    '',
    '## 🗺️ Symbol Guide',
    '',
    symbol_rows,
    '',
    '> **Keyboard shortcuts:** `Shift+Enter` run cell · `b` insert cell below · `m` convert to Markdown · `Esc` command mode',
)

objectives = [
    'Explain why PostgreSQL and PostGIS are standard choices for geospatial data systems',
    'Build safe database URLs and distinguish SQLite demo mode from PostgreSQL production mode',
    'Use DBAPI cursor patterns with parameterized queries and `%s` placeholders',
    'Define tables with SQLAlchemy Core and insert records with explicit metadata',
    'Design schemas for geospatial records with validation, indexing, and geometry text storage',
    'Create tables and understand the purpose of BTREE and GIST indexes',
    'Load data in bulk, fall back to row-by-row inserts, and capture duplicate errors',
    'Control transactions with commit, rollback, and nested savepoints',
    'Query tabular geospatial data and summarize results with SQL and pandas',
    'Write and test a reusable `spatial_etl.py` module for CSV-to-database workflows',
]
objective_rows = '\n'.join(f'| {i} | {text} |' for i, text in enumerate(objectives, start=1))
learning_objectives = md(
    '## 🎯 Learning Objectives',
    '',
    'By the end of this notebook you will be able to:',
    '',
    '| # | Objective |',
    '|---|-----------|',
    objective_rows,
    '',
    '### How to use this notebook',
    '',
    '- Run cells **top to bottom** in sequence',
    '- **Attempt** each 🎯 exercise before looking at the ✅ solution',
    '- Keep an eye on how SQLite demo code maps to PostgreSQL and PostGIS production workflows',
    '- The 🔬 **Mini-Lab** at the end turns the whole notebook into one ETL pipeline',
    '- Use the summary checklist before moving to Week 7 spatial queries',
)

environment = code(
    '# 💻 Environment check and auto-install',
    '# ─────────────────────────────────────────────────────────────────────────────',
    'import sys',
    'import subprocess',
    'import importlib',
    'import platform',
    '',
    'try:',
    '    import google.colab',
    '    IN_COLAB = True',
    'except ImportError:',
    '    IN_COLAB = False',
    '',
    'OS_NAME = platform.system()',
    '',
    'print("=" * 60)',
    'print("  Geospatial Python Mastery — Week 6 Environment Check")',
    'print("=" * 60)',
    "print(f\"  Environment : {'Google Colab' if IN_COLAB else 'Local Jupyter'}\")",
    'print(f"  Python      : {sys.version.split()[0]}")',
    'print(f"  OS          : {OS_NAME}")',
    'print()',
    '',
    'REQUIRED = [',
    '    ("pandas", "pandas", "1.3"),',
    '    ("sqlalchemy", "sqlalchemy", "1.4"),',
    '    ("psycopg2", "psycopg2-binary", "2.9"),',
    '    ("shapely", "shapely", "2.0"),',
    ']',
    '',
    'for import_name, pip_name, min_ver in REQUIRED:',
    '    try:',
    '        mod = importlib.import_module(import_name)',
    '        ver = getattr(mod, "__version__", "ok")',
    '        print(f"  ✅ {import_name:<20} {ver}")',
    '    except ImportError:',
    '        print(f"  ⬇  Installing {pip_name}…")',
    '        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pip_name])',
    '        print(f"  ✅ {pip_name} installed")',
    '',
    'if OS_NAME == "Windows":',
    '    print()',
    '    print("  ℹ  Windows note: PostgreSQL tools may need PATH updates after installation")',
    '    print("     Re-open Jupyter after installing psycopg2-binary or PostgreSQL client tools")',
    '',
    'print()',
    'print("✅ Environment check complete — ready for Week 6!")',
)

imports = lesson(
    '0.1',
    'Import database, file, and geometry helpers',
    'import csv',
    'import json',
    'import logging',
    'import sqlite3',
    'import sys',
    'from dataclasses import asdict',
    'from datetime import datetime, timezone',
    'from importlib import reload',
    'from pathlib import Path',
    '',
    'import pandas as pd',
    'import sqlalchemy as sa',
    'from shapely import from_wkt, to_wkt',
    'from shapely.geometry import Point',
    'from sqlalchemy import (',
    '    Boolean, CheckConstraint, Column, DateTime, Float, Integer, MetaData,',
    '    String, Table, create_engine, inspect, text',
    ')',
    'from sqlalchemy.exc import IntegrityError, SQLAlchemyError',
    '',
    'print("SQLAlchemy:", sa.__version__)',
    'print("pandas    :", pd.__version__)',
    'print("✅ Shared imports loaded")',
)

setup_dirs = lesson(
    '0.2',
    'Create week folders, logs, and stable paths',
    'def find_repo_root(start: Path) -> Path:',
    '    start = start.resolve()',
    '    for candidate in [start, *start.parents]:',
    '        if (candidate / "notebooks").exists() and (candidate / "instructions").exists():',
    '            return candidate',
    '    return start',
    '',
    'PROJECT_ROOT = find_repo_root(Path.cwd())',
    'COURSE_DIR = PROJECT_ROOT / "notebooks" / "geospatial_python_course"',
    'WEEK_DIR = COURSE_DIR / "data" / "week_06"',
    'INPUT_DIR = WEEK_DIR / "input"',
    'OUTPUT_DIR = WEEK_DIR / "output"',
    'LOG_DIR = COURSE_DIR / "logs"',
    '',
    'for path in [WEEK_DIR, INPUT_DIR, OUTPUT_DIR, LOG_DIR]:',
    '    path.mkdir(parents=True, exist_ok=True)',
    '',
    'print("Project root:", PROJECT_ROOT)',
    'print("Input dir   :", INPUT_DIR)',
    'print("Output dir  :", OUTPUT_DIR)',
    'print("Log dir     :", LOG_DIR)',
)

shared_helpers = lesson(
    '0.3',
    'Define small helpers used across the notebook',
    'def rows_to_frame(rows):',
    '    if not rows:',
    '        return pd.DataFrame()',
    '    first = rows[0]',
    '    if isinstance(first, sqlite3.Row):',
    '        return pd.DataFrame([dict(r) for r in rows])',
    '    if hasattr(first, "_mapping"):',
    '        return pd.DataFrame([dict(r._mapping) for r in rows])',
    '    return pd.DataFrame(rows)',
    '',
    'def utc_now_text():',
    '    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()',
    '',
    'logger = logging.getLogger("week6")',
    'logger.setLevel(logging.INFO)',
    'if not logger.handlers:',
    '    stream_handler = logging.StreamHandler()',
    '    stream_handler.setFormatter(logging.Formatter("%(levelname)s | %(message)s"))',
    '    logger.addHandler(stream_handler)',
    '',
    'print("Helper functions ready")',
)

sections = [
    {
        'title': 'Why PostgreSQL for Geospatial Data',
        'md_body': [
            'Relational databases make geospatial workflows repeatable. They support transactions, concurrent users, indexes, and SQL-based validation that go far beyond storing points in a flat file.',
            '',
            '### 1.1 Why SQL databases matter',
            '',
            '| Backend | Best use | Strengths | Limitations |',
            '|--------|----------|-----------|-------------|',
            '| **SQLite** | Local demos and portable teaching notebooks | Zero setup, single file, perfect for prototypes | Limited concurrency and no native spatial indexing extensions in this notebook |',
            '| **PostgreSQL** | Multi-user analytical systems | Strong transactions, roles, schemas, extensions, reliability | Needs a running server and admin setup |',
            '| **PostGIS** | Spatial analytics on PostgreSQL | Geometry types, SRIDs, GIST indexes, spatial functions | Requires PostgreSQL plus the PostGIS extension |',
            '',
            '> 💡 Use SQLite to learn the Python patterns. Use PostgreSQL when your workflow needs durability, multiple users, and production-grade data loading.',
        ],
        'code1_label': '1.2',
        'code1_title': 'Install/import block and configure DATA_DIR / DB_URL',
        'code1_body': [
            'DB_PATH = WEEK_DIR / "week6_demo.sqlite"',
            'DATA_DIR = WEEK_DIR',
            'DB_URL = f"sqlite:///{DB_PATH}"',
            'POSTGRES_URL_EXAMPLE = "postgresql+psycopg2://geo_user:secret@localhost:5432/geospatial_course"',
            '',
            'print("DATA_DIR              :", DATA_DIR)',
            'print("SQLite demo URL       :", DB_URL)',
            'print("PostgreSQL URL example:", POSTGRES_URL_EXAMPLE)',
            'print("💡 Change only DB_URL later if you want a live PostgreSQL connection.")',
        ],
        'code2_label': '1.3',
        'code2_title': 'Create an SQLAlchemy engine with echo=True and inspect metadata',
        'code2_body': [
            'engine = create_engine(DB_URL, echo=True, future=True)',
            'engine_info = {',
            '    "dialect": engine.dialect.name,',
            '    "driver": engine.dialect.driver,',
            '    "database": str(DB_PATH),',
            '}',
            '',
            'with engine.connect() as conn:',
            '    ping = conn.execute(text("SELECT 1 AS ping")).scalar_one()',
            '    print("Ping result:", ping)',
            '',
            'inspector = inspect(engine)',
            'print("Engine info:", engine_info)',
            'print("Tables visible at start:", inspector.get_table_names())',
        ],
        'exercise_title': 'Preview a backend switch',
        'exercise_task': 'Create a second engine variable and print its dialect name without changing the rest of the notebook.',
        'exercise_steps': [
            'Build a second SQLite URL such as `sqlite:///data/week_06/scratch.sqlite`.',
            'Create an engine from that URL.',
            'Print `engine.dialect.name` and `engine.dialect.driver`.',
        ],
        'exercise_hint': 'scratch_url = "sqlite:///data/week_06/scratch.sqlite"',
        'exercise_comments': [
            'Create a second database URL.',
            'Instantiate a second engine.',
            'Print the dialect and driver.',
        ],
        'solution_body': [
            'scratch_url = f"sqlite:///{WEEK_DIR / "scratch.sqlite"}"',
            'scratch_engine = create_engine(scratch_url, future=True)',
            'print("Dialect:", scratch_engine.dialect.name)',
            'print("Driver :", scratch_engine.dialect.driver)',
        ],
    },
    {
        'title': 'Direct DBAPI with psycopg2 (Simulation)',
        'md_body': [
            'The DBAPI is the low-level interface used by database drivers. For PostgreSQL, the most common Python driver is **psycopg2**.',
            '',
            '### 2.1 Connection strings and placeholders',
            '',
            '- `psycopg2.connect(...)` opens the connection directly to PostgreSQL.',
            '- `cursor.execute(sql, params)` keeps SQL and values separate.',
            '- psycopg2 always uses **`%s` placeholders** for parameters, regardless of data type.',
            '',
            '```text',
            'cur.execute("SELECT * FROM locations WHERE city = %s", ("Amsterdam",))',
            '```',
            '',
            '> ⚠️ Never build SQL with f-strings when values come from users or files. Parameterized queries protect you from SQL injection and awkward quoting bugs.',
        ],
        'code1_label': '2.2',
        'code1_title': 'Simulate a psycopg2-style workflow with sqlite3',
        'code1_body': [
            'SIM_DB = INPUT_DIR / "psycopg2_sim.sqlite"',
            '',
            'def get_sim_conn():',
            '    conn = sqlite3.connect(SIM_DB)',
            '    conn.row_factory = sqlite3.Row',
            '    return conn',
            '',
            'with get_sim_conn() as conn:',
            '    cur = conn.cursor()',
            '    cur.execute("DROP TABLE IF EXISTS locations")',
            '    cur.execute(',
            '        "CREATE TABLE locations (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, city TEXT NOT NULL, lon REAL NOT NULL, lat REAL NOT NULL)"',
            '    )',
            '    conn.commit()',
            '',
            'print("Created locations table in", SIM_DB)',
        ],
        'code2_label': '2.3',
        'code2_title': 'Insert rows and select with parameterized queries',
        'code2_body': [
            'demo_locations = [',
            '    ("Central Station", "Amsterdam", 4.9003, 52.3791),',
            '    ("Museumplein", "Amsterdam", 4.8811, 52.3579),',
            '    ("Centraal Station", "Rotterdam", 4.4688, 51.9244),',
            '    ("Binnenhof", "Den Haag", 4.3136, 52.0800),',
            ']',
            '',
            'with get_sim_conn() as conn:',
            '    cur = conn.cursor()',
            '    cur.executemany(',
            '        "INSERT INTO locations (name, city, lon, lat) VALUES (?, ?, ?, ?)",',
            '        demo_locations,',
            '    )',
            '    cur.execute("SELECT id, name, city, lon, lat FROM locations WHERE city = ? ORDER BY name", ("Amsterdam",))',
            '    rows = cur.fetchall()',
            '',
            'print(rows_to_frame(rows))',
        ],
        'exercise_title': 'Write a query helper by city',
        'exercise_task': 'Write a function that accepts a city name and returns matching rows from the simulated `locations` table.',
        'exercise_steps': [
            'Open a connection with `get_sim_conn()`.',
            'Execute a parameterized query with a tuple argument.',
            'Return or print the matching rows.',
        ],
        'exercise_hint': 'cur.execute("SELECT * FROM locations WHERE city = ?", (city_name,))',
        'exercise_comments': [
            'Define a function such as query_by_city(city_name).',
            'Execute a parameterized SELECT.',
            'Return rows or convert them to a DataFrame.',
        ],
        'solution_body': [
            'def query_by_city(city_name):',
            '    with get_sim_conn() as conn:',
            '        cur = conn.cursor()',
            '        cur.execute("SELECT name, city, lon, lat FROM locations WHERE city = ? ORDER BY name", (city_name,))',
            '        return cur.fetchall()',
            '',
            'print(rows_to_frame(query_by_city("Amsterdam")))',
        ],
    },
    {
        'title': 'SQLAlchemy Core (Cross-Database)',
        'md_body': [
            'SQLAlchemy Core gives you explicit control over tables, columns, and SQL while staying portable across database backends.',
            '',
            '### 3.1 Core vs ORM',
            '',
            '| Style | Best for | Why it matters this week |',
            '|------|----------|---------------------------|',
            '| **Core** | Data pipelines and ETL scripts | You control table definitions and bulk inserts directly |',
            '| **ORM** | Large applications with object models | Helpful later, but adds abstraction you do not need for loading files |',
            '',
            '> 💡 For data loading, SQLAlchemy Core is often the clearest layer between raw SQL and full ORM models.',
        ],
        'code1_label': '3.2',
        'code1_title': 'Define a spatial_records table with MetaData and Column objects',
        'code1_body': [
            'core_metadata = MetaData()',
            'spatial_records = Table(',
            '    "spatial_records",',
            '    core_metadata,',
            '    Column("id", Integer, primary_key=True),',
            '    Column("name", String(80), nullable=False),',
            '    Column("category", String(40), nullable=False),',
            '    Column("lon", Float, nullable=False),',
            '    Column("lat", Float, nullable=False),',
            '    Column("source", String(40), nullable=False, default="manual"),',
            ')',
            '',
            'print(spatial_records)',
            'print([c.name for c in spatial_records.columns])',
        ],
        'code2_label': '3.3',
        'code2_title': 'Use engine.begin() for inserts and SELECT with a WHERE clause',
        'code2_body': [
            'core_metadata.create_all(engine)',
            'seed_records = [',
            '    {"name": "Amsterdam", "category": "city", "lon": 4.9041, "lat": 52.3676, "source": "seed"},',
            '    {"name": "Rotterdam", "category": "city", "lon": 4.4777, "lat": 51.9244, "source": "seed"},',
            '    {"name": "Port of Rotterdam", "category": "infrastructure", "lon": 4.2900, "lat": 51.9500, "source": "seed"},',
            ']',
            '',
            'with engine.begin() as conn:',
            '    conn.execute(spatial_records.delete())',
            '    conn.execute(spatial_records.insert(), seed_records)',
            '    rows = conn.execute(',
            '        sa.select(spatial_records.c.name, spatial_records.c.category, spatial_records.c.lon, spatial_records.c.lat)',
            '        .where(spatial_records.c.category == "city")',
            '        .order_by(spatial_records.c.name)',
            '    ).fetchall()',
            '',
            'print(rows_to_frame(rows))',
        ],
        'exercise_title': 'Filter by category',
        'exercise_task': 'Extend the SELECT pattern so it accepts a `category` value and returns only matching rows.',
        'exercise_steps': [
            'Write a helper such as `fetch_spatial_records(category)`.',
            'Use `.where(spatial_records.c.category == category)`.',
            'Order the result by name.',
        ],
        'exercise_hint': 'sa.select(spatial_records).where(spatial_records.c.category == category)',
        'exercise_comments': [
            'Define a category filter helper.',
            'Execute the SELECT with a WHERE clause.',
            'Return the rows or print them as a DataFrame.',
        ],
        'solution_body': [
            'def fetch_spatial_records(category):',
            '    with engine.connect() as conn:',
            '        stmt = sa.select(spatial_records).where(spatial_records.c.category == category).order_by(spatial_records.c.name)',
            '        return conn.execute(stmt).fetchall()',
            '',
            'print(rows_to_frame(fetch_spatial_records("city")))',
        ],
    },
    {
        'title': 'Schema Design for Geospatial Records',
        'md_body': [
            'A good spatial schema balances clarity, validation, and future extensibility. Even before PostGIS geometry columns, you should plan names, data types, and integrity rules carefully.',
            '',
            '### 4.1 Schema design principles',
            '',
            '- Use descriptive column names such as `lon`, `lat`, `geom_wkt`, and `loaded_at`.',
            '- Separate **raw coordinates** from any derived geometry representation.',
            '- Preserve provenance with a `source` column.',
            '- Add validity flags or check constraints when coordinates must stay within world bounds.',
            '',
            '| Geometry storage option | Teaching value now | Production path later |',
            '|-------------------------|--------------------|-----------------------|',
            '| `lon` + `lat` columns | Easy to inspect | Keep for source data and CSV interoperability |',
            '| `geom_wkt` text | Human-readable geometry snapshot | Replace with PostGIS `geometry` later |',
            '| PostGIS `geometry(Point, 4326)` | Spatial indexing and functions | Primary production representation |',
        ],
        'code1_label': '4.2',
        'code1_title': 'Create a schema for geospatial records',
        'code1_body': [
            'schema_metadata = MetaData()',
            'city_assets = Table(',
            '    "city_assets",',
            '    schema_metadata,',
            '    Column("id", Integer, primary_key=True),',
            '    Column("name", String(80), nullable=False),',
            '    Column("category", String(40), nullable=False),',
            '    Column("lon", Float, nullable=False),',
            '    Column("lat", Float, nullable=False),',
            '    Column("geom_wkt", String(120), nullable=False),',
            '    Column("source", String(40), nullable=False),',
            '    Column("is_valid", Boolean, nullable=False, server_default=sa.true()),',
            '    Column("loaded_at", DateTime(timezone=True), nullable=False),',
            '    CheckConstraint("lon >= -180 AND lon <= 180", name="chk_city_assets_lon"),',
            '    CheckConstraint("lat >= -90 AND lat <= 90", name="chk_city_assets_lat"),',
            '    sa.UniqueConstraint("name", "source", name="uq_city_assets_name_source"),',
            ')',
            '',
            'print([c.name for c in city_assets.columns])',
        ],
        'code2_label': '4.3',
        'code2_title': 'Add indexes with DDL and inspect the CREATE TABLE statement',
        'code2_body': [
            'schema_metadata.create_all(engine)',
            'index_statements = [',
            '    "CREATE INDEX IF NOT EXISTS idx_city_assets_category ON city_assets (category)",',
            '    "CREATE INDEX IF NOT EXISTS idx_city_assets_loaded_at ON city_assets (loaded_at)",',
            ']',
            '',
            'with engine.begin() as conn:',
            '    for ddl in index_statements:',
            '        conn.execute(text(ddl))',
            '',
            'compiled_create = str(sa.schema.CreateTable(city_assets).compile(engine))',
            'print(compiled_create)',
            'print(index_statements)',
        ],
        'exercise_title': 'Inspect the geospatial schema',
        'exercise_task': 'Use the inspector to list the column names and think about which columns are raw input, validation metadata, and derived geometry text.',
        'exercise_steps': [
            'Call `inspect(engine).get_columns("city_assets")`.',
            'Print the column names.',
            'Comment on why `geom_wkt` is still useful before PostGIS.',
        ],
        'exercise_hint': 'cols = inspect(engine).get_columns("city_assets")',
        'exercise_comments': [
            'Inspect the city_assets table.',
            'Print the returned column metadata.',
            'Add a short comment about geom_wkt.',
        ],
        'solution_body': [
            'cols = inspect(engine).get_columns("city_assets")',
            'print([c["name"] for c in cols])',
            '# geom_wkt preserves a portable geometry representation even before a PostGIS geometry column exists.',
        ],
    },
    {
        'title': 'Creating Tables and Indexes',
        'md_body': [
            'DDL stands for Data Definition Language. It includes statements that create tables, add indexes, and define constraints.',
            '',
            '### 5.1 DDL, BTREE, and GIST',
            '',
            '| Index type | Typical target | Why it matters |',
            '|-----------|----------------|----------------|',
            '| **BTREE** | Text, numeric, and datetime columns | Fast equality and ordering queries |',
            '| **GIST** | PostGIS geometry columns | Powers bounding-box filtering and many spatial predicates |',
            '',
            '> 🐘 In SQLite we can demonstrate BTREE-style indexes. In PostgreSQL + PostGIS, spatial indexes are usually `USING GIST` on the geometry column.',
        ],
        'code1_label': '5.2',
        'code1_title': 'Create all tables and inspect what exists',
        'code1_body': [
            'core_metadata.create_all(engine)',
            'schema_metadata.create_all(engine)',
            'inspector = inspect(engine)',
            'table_names = inspector.get_table_names()',
            'print("Tables in the demo database:", table_names)',
            'for table_name in table_names:',
            '    column_names = [c["name"] for c in inspector.get_columns(table_name)]',
            '    print(f"- {table_name}: {column_names}")',
        ],
        'code2_label': '5.3',
        'code2_title': 'Print PostGIS-style CREATE INDEX statements',
        'code2_body': [
            'postgis_index_statements = [',
            '    "CREATE EXTENSION IF NOT EXISTS postgis;",',
            '    "CREATE INDEX idx_city_assets_geom ON city_assets USING GIST (geom);",',
            '    "CREATE INDEX idx_city_assets_category_btree ON city_assets USING BTREE (category);",',
            ']',
            '',
            'for ddl in postgis_index_statements:',
            '    print(ddl)',
        ],
        'exercise_title': 'Inspect tables and indexes',
        'exercise_task': 'Print the current tables and explain which columns would benefit from BTREE indexes versus a future GIST spatial index.',
        'exercise_steps': [
            'List tables with the inspector.',
            'List columns in `city_assets`.',
            'Note that `category` suits BTREE while a future geometry column suits GIST.',
        ],
        'exercise_hint': 'inspect(engine).get_table_names()',
        'exercise_comments': [
            'List tables in the database.',
            'Inspect columns for city_assets.',
            'Write a one-line comment about BTREE vs GIST.',
        ],
        'solution_body': [
            'insp = inspect(engine)',
            'print(insp.get_table_names())',
            'print([c["name"] for c in insp.get_columns("city_assets")])',
            '# BTREE fits category and loaded_at filters; GIST fits a future PostGIS geometry column.',
        ],
    },
    {
        'title': 'Inserting Data (Bulk and Row-by-Row)',
        'md_body': [
            'Loading data is more than calling INSERT once. Production ETL scripts usually try a fast bulk load first, then keep detailed error information for the records that fail.',
            '',
            '### 6.1 Insert strategies',
            '',
            '- **Bulk insert** is fast when all rows are valid.',
            '- **Row-by-row fallback** helps you capture which individual records failed.',
            '- **Structured logging** is essential when you load larger files repeatedly.',
            '',
            '> ⚠️ A duplicate key or invalid coordinate can cause a bulk insert to fail as one unit. That is why fallback logic is useful.',
        ],
        'code1_label': '6.2',
        'code1_title': 'Bulk insert a list of dictionaries',
        'code1_body': [
            'asset_rows = [',
            '    {"name": "Amsterdam", "category": "city", "lon": 4.9041, "lat": 52.3676, "geom_wkt": "POINT (4.9041 52.3676)", "source": "csv_seed", "is_valid": True, "loaded_at": datetime.now(timezone.utc)},',
            '    {"name": "Rotterdam", "category": "city", "lon": 4.4777, "lat": 51.9244, "geom_wkt": "POINT (4.4777 51.9244)", "source": "csv_seed", "is_valid": True, "loaded_at": datetime.now(timezone.utc)},',
            '    {"name": "Utrecht", "category": "city", "lon": 5.1214, "lat": 52.0907, "geom_wkt": "POINT (5.1214 52.0907)", "source": "csv_seed", "is_valid": True, "loaded_at": datetime.now(timezone.utc)},',
            '    {"name": "Port of Rotterdam", "category": "infrastructure", "lon": 4.2900, "lat": 51.9500, "geom_wkt": "POINT (4.2900 51.9500)", "source": "csv_seed", "is_valid": True, "loaded_at": datetime.now(timezone.utc)},',
            ']',
            '',
            'with engine.begin() as conn:',
            '    conn.execute(city_assets.delete())',
            '    conn.execute(city_assets.insert(), asset_rows)',
            '    total = conn.execute(text("SELECT COUNT(*) FROM city_assets")).scalar_one()',
            '',
            'print("Inserted rows:", total)',
        ],
        'code2_label': '6.3',
        'code2_title': 'Fall back to row-by-row inserts and capture errors',
        'code2_body': [
            'candidate_rows = [',
            '    {"name": "Amsterdam", "category": "city", "lon": 4.9041, "lat": 52.3676, "geom_wkt": "POINT (4.9041 52.3676)", "source": "csv_seed", "is_valid": True, "loaded_at": datetime.now(timezone.utc)},',
            '    {"name": "The Hague", "category": "city", "lon": 4.3007, "lat": 52.0705, "geom_wkt": "POINT (4.3007 52.0705)", "source": "csv_seed", "is_valid": True, "loaded_at": datetime.now(timezone.utc)},',
            ']',
            'errors = []',
            'inserted = 0',
            '',
            'for row in candidate_rows:',
            '    try:',
            '        with engine.begin() as conn:',
            '            conn.execute(city_assets.insert(), [row])',
            '        inserted += 1',
            '    except IntegrityError as exc:',
            '        errors.append({"name": row["name"], "reason": str(exc.orig)})',
            '',
            'print("Inserted after fallback:", inserted)',
            'print(pd.DataFrame(errors))',
        ],
        'exercise_title': 'Catch duplicate inserts with IntegrityError',
        'exercise_task': 'Write an insert function that catches `IntegrityError` and logs duplicate rows instead of stopping the whole load.',
        'exercise_steps': [
            'Loop over a list of record dictionaries.',
            'Insert one row at a time inside `engine.begin()`.',
            'Catch `IntegrityError` and append a short error note.',
        ],
        'exercise_hint': 'except IntegrityError as exc:\n    logger.warning("duplicate: %s", row["name"])',
        'exercise_comments': [
            'Define a safe insert helper.',
            'Catch IntegrityError inside the loop.',
            'Return inserted and rejected counts.',
        ],
        'solution_body': [
            'def safe_insert_rows(records):',
            '    inserted = 0',
            '    rejected = []',
            '    for row in records:',
            '        try:',
            '            with engine.begin() as conn:',
            '                conn.execute(city_assets.insert(), [row])',
            '            inserted += 1',
            '        except IntegrityError:',
            '            logger.warning("duplicate row skipped: %s", row["name"])',
            '            rejected.append(row["name"])',
            '    return inserted, rejected',
            '',
            'print(safe_insert_rows(candidate_rows))',
        ],
    },
    {
        'title': 'Transaction Management',
        'md_body': [
            'Transactions give you reliability. They define when a set of changes becomes permanent and what happens when an error occurs halfway through a load.',
            '',
            '### 7.1 ACID and savepoints',
            '',
            '- **Atomicity**: all steps succeed or none do.',
            '- **Consistency**: constraints still hold after the transaction.',
            '- **Isolation**: concurrent work does not corrupt your result.',
            '- **Durability**: committed changes stay committed.',
            '',
            '> 💡 `engine.begin()` is the cleanest pattern for many ETL tasks. Use nested transactions when you want a partial rollback inside a larger workflow.',
        ],
        'code1_label': '7.2',
        'code1_title': 'Compare engine.begin() with manual commit and rollback',
        'code1_body': [
            'with engine.begin() as conn:',
            '    conn.execute(text("DROP TABLE IF EXISTS transaction_notes"))',
            '    conn.execute(text("CREATE TABLE transaction_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL, value INTEGER NOT NULL CHECK (value >= 0))"))',
            '    conn.execute(text("INSERT INTO transaction_notes (label, value) VALUES (:label, :value)"), {"label": "committed row", "value": 1})',
            '',
            'try:',
            '    with engine.connect() as conn:',
            '        trans = conn.begin()',
            '        conn.execute(text("INSERT INTO transaction_notes (label, value) VALUES (:label, :value)"), {"label": "temporary row", "value": 2})',
            '        conn.execute(text("INSERT INTO transaction_notes (label, value) VALUES (:label, :value)"), {"label": "bad row", "value": -1})',
            '        trans.commit()',
            'except Exception as exc:',
            '    print("Rollback triggered:", exc)',
            '    trans.rollback()',
            '',
            'with engine.connect() as conn:',
            '    rows = conn.execute(text("SELECT label, value FROM transaction_notes ORDER BY id")).fetchall()',
            'print(rows_to_frame(rows))',
        ],
        'code2_label': '7.3',
        'code2_title': 'Simulate a nested transaction with a savepoint',
        'code2_body': [
            'with engine.begin() as conn:',
            '    conn.execute(text("DROP TABLE IF EXISTS nested_demo"))',
            '    conn.execute(text("CREATE TABLE nested_demo (id INTEGER PRIMARY KEY, note TEXT NOT NULL)"))',
            '',
            'with engine.connect() as conn:',
            '    outer = conn.begin()',
            '    conn.execute(text("INSERT INTO nested_demo (id, note) VALUES (1, "outer start")"))',
            '    savepoint = conn.begin_nested()',
            '    try:',
            '        conn.execute(text("INSERT INTO nested_demo (id, note) VALUES (2, "nested ok")"))',
            '        conn.execute(text("INSERT INTO nested_demo (id, note) VALUES (2, "nested duplicate")"))',
            '        savepoint.commit()',
            '    except Exception as exc:',
            '        print("Nested failure:", exc)',
            '        savepoint.rollback()',
            '    conn.execute(text("INSERT INTO nested_demo (id, note) VALUES (3, "outer survives")"))',
            '    outer.commit()',
            '',
            'with engine.connect() as conn:',
            '    rows = conn.execute(text("SELECT * FROM nested_demo ORDER BY id")).fetchall()',
            'print(rows_to_frame(rows))',
        ],
        'exercise_title': 'Summarize transaction results',
        'exercise_task': 'Query the two transaction demo tables and explain which rows survived and why.',
        'exercise_steps': [
            'Read rows from `transaction_notes` and `nested_demo`.',
            'Compare committed rows with rolled-back rows.',
            'Add a short comment about the savepoint behavior.',
        ],
        'exercise_hint': 'rows = conn.execute(text("SELECT * FROM nested_demo")).fetchall()',
        'exercise_comments': [
            'Query transaction_notes.',
            'Query nested_demo.',
            'Add one explanatory comment.',
        ],
        'solution_body': [
            'with engine.connect() as conn:',
            '    print(rows_to_frame(conn.execute(text("SELECT * FROM transaction_notes ORDER BY id")).fetchall()))',
            '    print(rows_to_frame(conn.execute(text("SELECT * FROM nested_demo ORDER BY id")).fetchall()))',
            '# The bad manual insert rolled back, while the outer transaction survived the nested savepoint failure.',
        ],
    },
    {
        'title': 'Querying Data',
        'md_body': [
            'Reading data back is how you verify a load, troubleshoot anomalies, and create analytical summaries for later spatial queries.',
            '',
            '### 8.1 SELECT patterns, filtering, and aggregation',
            '',
            '- Use `text()` when you want to write SQL directly.',
            '- Keep filters parameterized with named parameters such as `:category`.',
            '- Convert result sets to pandas when you want tabular summaries or quick visual inspection.',
        ],
        'code1_label': '8.2',
        'code1_title': 'Use text() with parameters and convert the result to a DataFrame',
        'code1_body': [
            'with engine.connect() as conn:',
            '    rows = conn.execute(',
            '        text("SELECT name, category, lon, lat FROM city_assets WHERE category = :category ORDER BY name"),',
            '        {"category": "city"},',
            '    ).fetchall()',
            '',
            'city_df = rows_to_frame(rows)',
            'print(city_df)',
        ],
        'code2_label': '8.3',
        'code2_title': 'GROUP BY category, ORDER BY count, and LIMIT the output',
        'code2_body': [
            'with engine.connect() as conn:',
            '    summary_rows = conn.execute(',
            '        text("SELECT category, COUNT(*) AS n_records FROM city_assets GROUP BY category ORDER BY n_records DESC, category LIMIT 10")',
            '    ).fetchall()',
            '',
            'summary_df = rows_to_frame(summary_rows)',
            'print(summary_df.to_string(index=False))',
        ],
        'exercise_title': 'Count records where latitude is above 50',
        'exercise_task': 'Filter records where `lat > 50` and count them by category.',
        'exercise_steps': [
            'Write a SELECT with a `WHERE lat > :cutoff` clause.',
            'Group by `category`.',
            'Order by the count descending.',
        ],
        'exercise_hint': 'text("SELECT category, COUNT(*) FROM city_assets WHERE lat > :cutoff GROUP BY category")',
        'exercise_comments': [
            'Write a parameterized aggregation query.',
            'Execute it with cutoff 50.',
            'Print the grouped result.',
        ],
        'solution_body': [
            'with engine.connect() as conn:',
            '    lat_summary = conn.execute(',
            '        text("SELECT category, COUNT(*) AS n_records FROM city_assets WHERE lat > :cutoff GROUP BY category ORDER BY n_records DESC, category"),',
            '        {"cutoff": 50},',
            '    ).fetchall()',
            '',
            'print(rows_to_frame(lat_summary))',
        ],
    },
    {
        'title': 'PostGIS Setup and Spatial Columns',
        'md_body': [
            'PostGIS adds geometry types, SRIDs, and spatial functions to PostgreSQL. You still need to think clearly about coordinate reference systems and whether geometry or geography fits the task.',
            '',
            '### 9.1 Geometry, geography, and SRID',
            '',
            '| Term | Meaning | Common use |',
            '|------|---------|------------|',
            '| **geometry** | Planar spatial type with an assigned SRID | Most vector analytics in projected or geographic CRS |',
            '| **geography** | Spheroidal type for Earth-distance calculations | Simpler great-circle style distance cases |',
            '| **SRID 4326** | WGS84 longitude/latitude | Standard storage for global point data |',
            '',
            '> 🐘 The code below prints PostgreSQL/PostGIS DDL as strings because the runnable demo engine is SQLite.',
        ],
        'code1_label': '9.2',
        'code1_title': 'Print PostgreSQL and PostGIS DDL statements',
        'code1_body': [
            'postgis_ddls = [',
            '    "CREATE EXTENSION IF NOT EXISTS postgis;",',
            '    "CREATE TABLE city_assets_postgis (id SERIAL PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, geom geometry(POINT, 4326) NOT NULL);",',
            '    "CREATE INDEX idx_city_assets_postgis_geom ON city_assets_postgis USING GIST (geom);",',
            ']',
            '',
            'for ddl in postgis_ddls:',
            '    print(ddl)',
        ],
        'code2_label': '9.3',
        'code2_title': 'Round-trip WKT through Shapely',
        'code2_body': [
            'wkt_point = "POINT (4.9041 52.3676)"',
            'geom = from_wkt(wkt_point)',
            'round_trip_wkt = to_wkt(geom, rounding_precision=4)',
            '',
            'print("Geometry type:", geom.geom_type)',
            'print("Coordinates   :", list(geom.coords)[0])',
            'print("Round-trip WKT:", round_trip_wkt)',
        ],
        'exercise_title': 'Create another WKT point',
        'exercise_task': 'Build a WKT point for Rotterdam, load it with Shapely, and print the coordinates.',
        'exercise_steps': [
            'Write a WKT string such as `POINT (4.4777 51.9244)`.',
            'Call `from_wkt(...)`.',
            'Print the coordinate tuple.',
        ],
        'exercise_hint': 'geom = from_wkt("POINT (4.4777 51.9244)")',
        'exercise_comments': [
            'Create a Rotterdam WKT string.',
            'Convert it to a geometry.',
            'Print the coordinate pair.',
        ],
        'solution_body': [
            'rotterdam_geom = from_wkt("POINT (4.4777 51.9244)")',
            'print(list(rotterdam_geom.coords)[0])',
        ],
    },
    {
        'title': 'Spatial ETL Module',
        'md_body': [
            'The goal of this section is to move from one-off notebook cells to a reusable ETL module. The module validates rows, loads them into a table, verifies the result, and returns a structured report.',
            '',
            '### 10.1 ETL design principles',
            '',
            '| ETL stage | Responsibility | Why it matters |',
            '|-----------|----------------|----------------|',
            '| Extract | Read CSV rows into dictionaries | Keeps file parsing separate from database logic |',
            '| Transform | Validate names and coordinate ranges, build WKT | Prevents invalid rows from reaching the table |',
            '| Load | Bulk insert, then row-by-row fallback | Balances speed with detailed error reporting |',
            '| Verify | Compare row counts after load | Confirms the pipeline produced the expected result |',
            '| Report | Return a JSON-serializable summary | Makes logging and automation easier |',
        ],
        'code1_label': '10.2',
        'code1_title': 'Write the spatial_etl.py module to disk',
        'code1_body': [
            '%%writefile spatial_etl.py',
            'import csv',
            'from dataclasses import dataclass',
            'from datetime import datetime, timezone',
            '',
            'from sqlalchemy import text',
            'from sqlalchemy.exc import IntegrityError, SQLAlchemyError',
            '',
            '',
            'class ValidationError(ValueError):',
            '    pass',
            '',
            '',
            '@dataclass',
            'class LoadResult:',
            '    table: str',
            '    inserted: int',
            '    rejected: int',
            '    errors: list',
            '    started: str',
            '    finished: str',
            '',
            '    def summary(self):',
            '        return {',
            '            "table": self.table,',
            '            "inserted": self.inserted,',
            '            "rejected": self.rejected,',
            '            "error_count": len(self.errors),',
            '            "started": self.started,',
            '            "finished": self.finished,',
            '        }',
            '',
            '',
            'def validate_record(r):',
            '    name = str(r.get("name", "")).strip()',
            '    if not name:',
            '        raise ValidationError("name must not be blank")',
            '    lon = float(r.get("lon"))',
            '    lat = float(r.get("lat"))',
            '    if not (-180 <= lon <= 180):',
            '        raise ValidationError("lon must be within -180..180")',
            '    if not (-90 <= lat <= 90):',
            '        raise ValidationError("lat must be within -90..90")',
            '    category = str(r.get("category", "unknown")).strip() or "unknown"',
            '    source = str(r.get("source", "csv")).strip() or "csv"',
            '    return {',
            '        "name": name,',
            '        "category": category,',
            '        "lon": lon,',
            '        "lat": lat,',
            '        "geom_wkt": f"POINT ({lon} {lat})",',
            '        "source": source,',
            '        "is_valid": True,',
            '        "loaded_at": datetime.now(timezone.utc),',
            '    }',
            '',
            '',
            'def load_records(records, engine, table):',
            '    started = datetime.now(timezone.utc).isoformat()',
            '    valid_rows = []',
            '    errors = []',
            '    for i, record in enumerate(records, start=1):',
            '        try:',
            '            valid_rows.append(validate_record(record))',
            '        except ValidationError as exc:',
            '            errors.append({"row": i, "name": record.get("name", ""), "error": str(exc)})',
            '',
            '    insert_sql = text(',
            '        f"INSERT INTO {table} (name, category, lon, lat, geom_wkt, source, is_valid, loaded_at) "',
            '        "VALUES (:name, :category, :lon, :lat, :geom_wkt, :source, :is_valid, :loaded_at)"',
            '    )',
            '    inserted = 0',
            '    if valid_rows:',
            '        try:',
            '            with engine.begin() as conn:',
            '                conn.execute(insert_sql, valid_rows)',
            '            inserted = len(valid_rows)',
            '        except SQLAlchemyError:',
            '            for row in valid_rows:',
            '                try:',
            '                    with engine.begin() as conn:',
            '                        conn.execute(insert_sql, [row])',
            '                    inserted += 1',
            '                except IntegrityError as exc:',
            '                    errors.append({"row": row["name"], "error": str(exc.orig)})',
            '                except SQLAlchemyError as exc:',
            '                    errors.append({"row": row["name"], "error": str(exc)})',
            '',
            '    finished = datetime.now(timezone.utc).isoformat()',
            '    return LoadResult(',
            '        table=table,',
            '        inserted=inserted,',
            '        rejected=len(errors),',
            '        errors=errors,',
            '        started=started,',
            '        finished=finished,',
            '    )',
            '',
            '',
            'def verify_load(table, n_expected, engine):',
            '    with engine.connect() as conn:',
            '        loaded = conn.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar_one()',
            '    return {"table": table, "expected": n_expected, "loaded": loaded, "ok": loaded == n_expected}',
            '',
            '',
            'def run_etl(csv_path, engine, table):',
            '    with open(csv_path, newline="", encoding="utf-8") as fh:',
            '        records = list(csv.DictReader(fh))',
            '    result = load_records(records, engine, table)',
            '    verification = verify_load(table, result.inserted, engine)',
            '    return {',
            '        "table": table,',
            '        "records_read": len(records),',
            '        "load_result": result.summary(),',
            '        "errors": result.errors,',
            '        "verification": verification,',
            '    }',
        ],
        'code2_label': '10.3',
        'code2_title': 'Import spatial_etl and run quick unit tests',
        'code2_body': [
            'if str(Path.cwd()) not in sys.path:',
            '    sys.path.insert(0, str(Path.cwd()))',
            '',
            'import spatial_etl',
            'reload(spatial_etl)',
            '',
            'TEST_TABLE = "etl_test_records"',
            'with engine.begin() as conn:',
            '    conn.execute(text(f"DROP TABLE IF EXISTS {TEST_TABLE}"))',
            '    conn.execute(text(f"CREATE TABLE {TEST_TABLE} (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, category TEXT NOT NULL, lon REAL NOT NULL, lat REAL NOT NULL, geom_wkt TEXT NOT NULL, source TEXT NOT NULL, is_valid BOOLEAN NOT NULL, loaded_at TIMESTAMP NOT NULL, UNIQUE(name, source))"))',
            '',
            'clean = spatial_etl.validate_record({"name": "Leiden", "category": "city", "lon": 4.4970, "lat": 52.1601, "source": "unit"})',
            'assert clean["geom_wkt"].startswith("POINT")',
            '',
            'result = spatial_etl.load_records([',
            '    {"name": "Leiden", "category": "city", "lon": 4.4970, "lat": 52.1601, "source": "unit"},',
            '    {"name": "", "category": "broken", "lon": 4.0, "lat": 52.0, "source": "unit"},',
            '], engine, TEST_TABLE)',
            'assert result.inserted == 1',
            'assert result.rejected == 1',
            'assert spatial_etl.verify_load(TEST_TABLE, 1, engine)["ok"] is True',
            'print(result.summary())',
        ],
        'exercise_title': 'Extend the ETL report to JSON output',
        'exercise_task': 'Modify `run_etl` so it also writes the final report dictionary to disk as JSON.',
        'exercise_steps': [
            'Add a `report_path` argument to the function signature.',
            'Write the report with `json.dumps(report, indent=2, default=str)`.',
            'Return the report as before.',
        ],
        'exercise_hint': 'Path(report_path).write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")',
        'exercise_comments': [
            'Add a new report_path parameter.',
            'Write the report JSON to disk.',
            'Return the report dictionary.',
        ],
        'solution_body': [
            'from pathlib import Path',
            'import json',
            '',
            'def run_etl_with_report(csv_path, engine, table, report_path):',
            '    report = spatial_etl.run_etl(csv_path, engine, table)',
            '    Path(report_path).write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")',
            '    return report',
            '',
            'print("Helper ready for a file-backed JSON ETL report")',
        ],
    },
]

lab_intro = md(
    '---',
    '## 🔬 Mini-Lab — City Records ETL Pipeline',
    '',
    '**Scenario:** You have received a CSV of city records from multiple sources. Your task is to validate it, load the clean rows into a database table, and write a JSON report that documents what happened.',
    '',
    '**Mini-Lab steps:**',
    '1. Create the CSV file with 12 rows, including 2 invalid rows',
    '2. Create the database table for the ETL target',
    '3. Preview and validate the CSV rows before loading',
    '4. Run the ETL module',
    '5. Verify the load with a SELECT query and pandas',
    '6. Write the ETL report to JSON',
)

lab_steps = [
    labstep(
        1,
        'Create the CSV file',
        'CSV_PATH = INPUT_DIR / "city_records_lab.csv"',
        'lab_rows = [',
        '    {"name": "Amsterdam", "category": "city", "lon": 4.9041, "lat": 52.3676, "source": "survey"},',
        '    {"name": "Rotterdam", "category": "city", "lon": 4.4777, "lat": 51.9244, "source": "survey"},',
        '    {"name": "Utrecht", "category": "city", "lon": 5.1214, "lat": 52.0907, "source": "survey"},',
        '    {"name": "Groningen", "category": "city", "lon": 6.5665, "lat": 53.2194, "source": "survey"},',
        '    {"name": "Eindhoven", "category": "city", "lon": 5.4697, "lat": 51.4416, "source": "survey"},',
        '    {"name": "Leiden", "category": "city", "lon": 4.4970, "lat": 52.1601, "source": "survey"},',
        '    {"name": "Delft", "category": "city", "lon": 4.3571, "lat": 52.0116, "source": "survey"},',
        '    {"name": "The Hague", "category": "city", "lon": 4.3007, "lat": 52.0705, "source": "survey"},',
        '    {"name": "Zwolle", "category": "city", "lon": 6.0944, "lat": 52.5168, "source": "survey"},',
        '    {"name": "Arnhem", "category": "city", "lon": 5.8987, "lat": 51.9851, "source": "survey"},',
        '    {"name": "", "category": "city", "lon": 4.0, "lat": 52.0, "source": "survey"},',
        '    {"name": "BrokenPoint", "category": "city", "lon": 999.0, "lat": 95.0, "source": "survey"},',
        ']',
        '',
        'with CSV_PATH.open("w", newline="", encoding="utf-8") as fh:',
        '    writer = csv.DictWriter(fh, fieldnames=["name", "category", "lon", "lat", "source"])',
        '    writer.writeheader()',
        '    writer.writerows(lab_rows)',
        '',
        'print("Wrote CSV to:", CSV_PATH)',
    ),
    labstep(
        2,
        'Create the database table',
        'LAB_TABLE = "city_etl_records"',
        'with engine.begin() as conn:',
        '    conn.execute(text(f"DROP TABLE IF EXISTS {LAB_TABLE}"))',
        '    conn.execute(text(f"CREATE TABLE {LAB_TABLE} (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, category TEXT NOT NULL, lon REAL NOT NULL, lat REAL NOT NULL, geom_wkt TEXT NOT NULL, source TEXT NOT NULL, is_valid BOOLEAN NOT NULL, loaded_at TIMESTAMP NOT NULL, UNIQUE(name, source))"))',
        '',
        'print("Created table:", LAB_TABLE)',
    ),
    labstep(
        3,
        'Preview and validate the CSV',
        'with CSV_PATH.open(newline="", encoding="utf-8") as fh:',
        '    preview_rows = list(csv.DictReader(fh))',
        '',
        'valid_count = 0',
        'invalid_rows = []',
        'for row in preview_rows:',
        '    try:',
        '        spatial_etl.validate_record(row)',
        '        valid_count += 1',
        '    except spatial_etl.ValidationError as exc:',
        '        invalid_rows.append({"name": row.get("name", ""), "error": str(exc)})',
        '',
        'print("Rows read   :", len(preview_rows))',
        'print("Valid rows  :", valid_count)',
        'print("Invalid rows:")',
        'print(pd.DataFrame(invalid_rows))',
    ),
    labstep(
        4,
        'Run the ETL',
        'lab_report = spatial_etl.run_etl(CSV_PATH, engine, LAB_TABLE)',
        'print(json.dumps(lab_report, indent=2, default=str))',
    ),
    labstep(
        5,
        'Verify the load',
        'with engine.connect() as conn:',
        '    loaded_rows = conn.execute(text(f"SELECT name, category, lon, lat, source FROM {LAB_TABLE} ORDER BY name")).fetchall()',
        '',
        'loaded_df = rows_to_frame(loaded_rows)',
        'print(loaded_df)',
    ),
    labstep(
        6,
        'Write the JSON report',
        'report_path = OUTPUT_DIR / "city_etl_report.json"',
        'report_path.write_text(json.dumps(lab_report, indent=2, default=str), encoding="utf-8")',
        'print(report_path.read_text(encoding="utf-8"))',
        'print("Saved report to:", report_path)',
    ),
]

extension = md(
    '### 🚀 Extension Ideas',
    '',
    '- Replace the SQLite URL with a local PostgreSQL database and rerun the notebook end to end',
    '- Add a true PostGIS `geometry(Point, 4326)` column and compare it with `geom_wkt`',
    '- Extend `spatial_etl.py` so it writes logs and rejects invalid rows to a CSV audit file',
)

summary_rows = '\n'.join([
    '| Section 1 | Why PostgreSQL matters and how SQLite demo mode maps to a server-backed workflow |',
    '| Section 2 | DBAPI cursor patterns and safe parameterized queries |',
    '| Section 3 | SQLAlchemy Core table definitions and portable inserts |',
    '| Section 4 | Schema design with validation, provenance, and geometry text storage |',
    '| Section 5 | DDL, inspector usage, BTREE indexes, and PostGIS GIST concepts |',
    '| Section 6 | Bulk inserts, fallback logic, and duplicate handling |',
    '| Section 7 | Commit, rollback, and nested transaction behavior |',
    '| Section 8 | SELECT, aggregation, ordering, and DataFrame inspection |',
    '| Section 9 | PostGIS extension setup, geometry vs geography, and SRID awareness |',
    '| Section 10 | Reusable ETL module design for validation, loading, verification, and reporting |',
])
preview_rows = '\n'.join([
    '| PostGIS spatial functions | Understand how PostGIS extends SQL with geometry-aware functions |',
    '| `ST_Intersects` | Filter features that overlap or touch in space |',
    '| `ST_Buffer` | Build distance-based zones around points and lines |',
    '| spatial indexes | Use GIST indexes to accelerate spatial predicates |',
    '| `EXPLAIN ANALYZE` | Read query plans and reason about performance |',
])
reading_rows = '\n'.join([
    '| [psycopg2 docs](https://www.psycopg.org/docs/) | Official DBAPI driver reference for PostgreSQL |',
    '| [SQLAlchemy docs](https://docs.sqlalchemy.org/) | Core tables, engines, and database portability |',
    '| [PostGIS docs](https://postgis.net/documentation/) | Spatial types, functions, and indexing guidance |',
    '| [pgAdmin](https://www.pgadmin.org/) | GUI tool for exploring PostgreSQL and PostGIS databases |',
    '| [PostgreSQL tutorial](https://www.postgresqltutorial.com/) | Friendly walkthrough of PostgreSQL SQL basics |',
])

final_summary = md(
    '---',
    '## ✅ Week 6 Summary',
    '',
    '| Section | Key concept |',
    '|--------|-------------|',
    summary_rows,
    '',
    '---',
    '',
    '### ☑️ Self-assessment checklist',
    '',
    '- [ ] Explain when SQLite is enough and when PostgreSQL is the better choice',
    '- [ ] Build a database URL and identify its dialect and driver',
    '- [ ] Write a parameterized DBAPI query instead of using string interpolation',
    '- [ ] Define a table with SQLAlchemy Core and inspect its columns',
    '- [ ] Explain why `lon`, `lat`, and `geom_wkt` can coexist in one schema',
    '- [ ] Describe the difference between BTREE and GIST indexes',
    '- [ ] Load rows in bulk and explain why row-by-row fallback is useful',
    '- [ ] Show what rollback does after a failed insert',
    '- [ ] Write a grouped SQL query and load the result into pandas',
    '- [ ] Describe how the ETL module validates, loads, verifies, and reports',
    '',
    '---',
    '',
    '## 📚 Week 7 Preview',
    '',
    '| Topic | What you will learn |',
    '|-------|---------------------|',
    preview_rows,
    '',
    '---',
    '',
    '## 📖 Further Reading',
    '',
    '| Resource | Why |',
    '|----------|-----|',
    reading_rows,
    '',
    '---',
    '',
    '*Next: Week 7 — PostGIS Spatial Queries*',
)

C = [week_title, learning_objectives, environment, imports, setup_dirs, shared_helpers]
for idx, section in enumerate(sections, start=1):
    C.append(md('---', f'## 📖 Section {idx} — {section["title"]}', '', *section['md_body']))
    C.append(lesson(section['code1_label'], section['code1_title'], *section['code1_body']))
    C.append(lesson(section['code2_label'], section['code2_title'], *section['code2_body']))
    C.append(exmd(idx, section['exercise_title'], section['exercise_task'], section['exercise_steps'], section['exercise_hint']))
    C.append(exstub(idx, section['exercise_comments']))
    C.append(exsol(idx, *section['solution_body']))

C.append(lab_intro)
C.extend(lab_steps)
C.append(extension)
C.append(final_summary)

notebook = {
    'cells': C,
    'metadata': metadata,
    'nbformat': 4,
    'nbformat_minor': 5,
}

OUT.write_text(json.dumps(notebook, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
print(f'Wrote {OUT} with {len(C)} cells')
