import json
import uuid
from pathlib import Path


def cell_id():
    return uuid.uuid4().hex[:12]


def lines(*args):
    '''Join args with newlines, return as list of 'line\n' strings.'''
    result = []
    for a in args:
        for ln in str(a).split('\n'):
            result.append(ln + '\n')
    if result:
        result[-1] = result[-1].rstrip('\n')
    return result


def md(*parts, cid=None):
    return {'cell_type': 'markdown', 'id': cid or cell_id(), 'metadata': {}, 'source': lines(*parts)}


def code(*parts, cid=None):
    return {
        'cell_type': 'code',
        'id': cid or cell_id(),
        'metadata': {},
        'execution_count': None,
        'outputs': [],
        'source': lines(*parts),
    }


def lesson(label, title, *body):
    return code(f'# 💻 {label}  {title}', '# ─────────────────────────────────────────────────────────────────────────────', *body)


def exmd(num, title, task, steps, hint):
    step_lines = [f'{i}. {step}' for i, step in enumerate(steps, start=1)]
    return md(
        f'### 🎯 Exercise {num} — {title}',
        '',
        f'**Task:** {task}',
        '',
        '**Steps:**',
        *step_lines,
        '',
        '**Hint:**',
        '',
        '```python',
        hint,
        '```',
    )


def exstub(num, comments):
    body = [f'# {i}. {comment}' for i, comment in enumerate(comments, start=1)]
    return code(f'# 🎯 Exercise {num} — your code here ────────────────────────────────', *body)


def exsol(num, *body):
    return code(f'# ✅ Exercise {num} — Solution ──────────────────────────────────────', *body)


def labstep(num, title, *body):
    return code(f'# 🔬 Step {num} — {title}', '# ─────────────────────────────────────────────────────────────────────────────', *body)


REPO_ROOT = Path(__file__).resolve().parents[3]
OUT = REPO_ROOT / 'notebooks' / 'geospatial_python_course' / 'week_07_postgis_core_queries.ipynb'
OUT.parent.mkdir(parents=True, exist_ok=True)

metadata = {
    'kernelspec': {
        'display_name': 'Python 3 (ipykernel)',
        'language': 'python',
        'name': 'python3',
    },
    'language_info': {
        'codemirror_mode': {'name': 'ipython', 'version': 3},
        'file_extension': '.py',
        'mimetype': 'text/x-python',
        'name': 'python',
        'pygments_lexer': 'ipython3',
        'version': '3.11.0',
    },
    'toc-autonumbering': False,
}

section_topics = [
    'Spatial Types and PostGIS Architecture',
    'Spatial Indexes and Query Planning',
    'ST_Intersects and ST_Within',
    'ST_Buffer and ST_Area',
    'ST_DWithin — Distance Queries',
    'ST_Transform — Coordinate Reference Systems',
    'Combining Spatial Functions',
    'Running PostGIS Queries from Python',
    'EXPLAIN ANALYZE and Performance',
    'Mini-Lab: Urban Planning Questions',
]

toc_rows = '\n'.join(f'| {i} | {title} |' for i, title in enumerate(section_topics, start=1))
objective_rows = '\n'.join([
    '| 1 | Explain PostGIS geometry types: Point, LineString, Polygon, MultiPolygon |',
    '| 2 | Create and use GiST spatial indexes for fast bounding-box queries |',
    '| 3 | Write ST_Intersects queries to find overlapping geometries |',
    '| 4 | Use ST_Within to test containment between features |',
    '| 5 | Buffer geometries with ST_Buffer and compute areas with ST_Area |',
    '| 6 | Run distance queries with ST_DWithin (faster than ST_Distance) |',
    '| 7 | Transform coordinates with ST_Transform between SRID 4326 and 28992 |',
    '| 8 | Chain spatial functions in a single SELECT |',
    '| 9 | Execute PostGIS SQL from Python using SQLAlchemy text() |',
    '| 10 | Read EXPLAIN ANALYZE output to diagnose slow spatial queries |',
])

week_title = md(
    '# 🌍 Week 7 — PostGIS Core Queries',
    '### Geospatial Python Mastery | Module 4: Spatial Databases',
    '---',
    '| | |',
    '|---|---|',
    '| **Module** | Module 4: Spatial Databases |',
    '| **Week** | 7 of 10 |',
    '| **Duration** | ~3 hours |',
    '| **Level** | Intermediate-Advanced |',
    '| **Prerequisites** | Weeks 1–6 (Python, GeoPandas, PostgreSQL/SQLAlchemy) |',
    '',
    '> In this week you master the core PostGIS spatial functions that power real-world urban analysis: ',
    '> buffering, intersection tests, distance queries, area calculations, and coordinate transforms. ',
    "> You'll also learn how spatial indexes (GiST) and query planning make large datasets fast.",
    '',
    '### 🧭 Workflow for this session',
    '- Start with geometry vocabulary, storage formats, and the SRID mindset.',
    '- Learn how GiST indexes narrow search space before exact geometry checks run.',
    '- Practice the three core predicate families used constantly in production: overlap, containment, and distance.',
    '- Reproject before metric analysis so buffers, area, and distance have meaningful units.',
    '- Finish by reading query plans and packaging database results into Python workflows.',
    '',
    '### 🗺️ Practical lens',
    '- Every 🔷 demo-safe cell mirrors a real 🐘 PostGIS pattern.',
    '- The notebook keeps Dutch examples explicit about **EPSG:4326** versus **EPSG:28992** so CRS thinking becomes habitual.',
    '- The mini-lab at the end turns the separate functions into a realistic planning workflow with filtering, classification, transformation, and export.',
    '',
    '### 📋 Table of Contents',
    '| # | Section |',
    '|---|---------|',
    toc_rows,
    '',
    '### 🔣 Symbol Guide',
    '| Symbol | Meaning |',
    '|--------|---------|',
    '| 💻 | Code walkthrough |',
    '| 🎯 | Exercise |',
    '| ✅ | Solution |',
    '| 🔬 | Lab step |',
    '| 🐘 | PostgreSQL/PostGIS only |',
    '| 🔷 | Runs in demo (SQLite + Shapely) |',
    '| 📖 | Concept explanation |',
    '',
    '*Press `Shift+Enter` to run a cell. `Ctrl+/` to comment/uncomment.*',
)

learning_objectives = md(
    '## 🎯 Learning Objectives',
    '',
    'By the end of this week you will be able to:',
    '',
    '| # | Objective |',
    '|---|-----------|',
    objective_rows,
    '',
    '**How to use this notebook:**',
    '- 🔷 cells run without a PostgreSQL server (Shapely + SQLite demo)',
    '- 🐘 cells show the exact PostGIS SQL to run on a real server',
    '- Exercises have stubs you fill in, then reveal the solution',
    '',
    '**Suggested pacing:**',
    '| Phase | Focus | Approx. time |',
    '|------|-------|--------------|',
    '| Warm-up | Geometry types, WKT/WKB, and SRID review | 20 min |',
    '| Query core | Intersects, Within, Buffer, Area, DWithin | 70 min |',
    '| CRS practice | Transforming Dutch data correctly | 20 min |',
    '| Python integration | SQLAlchemy + GeoPandas workflow | 30 min |',
    '| Performance | EXPLAIN ANALYZE and spatial indexes | 20 min |',
    '| Mini-lab | End-to-end planning questions | 40 min |',
    '',
    '**Mental model to keep throughout the notebook:**',
    '- Ask **what CRS and units** your geometry currently uses before you measure anything.',
    '- Ask **whether the predicate can use an index** before you write a production WHERE clause.',
    '- Ask **whether the work belongs in SQL or Python** before you move data out of PostGIS.',
)

environment = code(
    '# ── Environment detection and package installation ────────────────────────────',
    'import sys, subprocess',
    '',
    "IN_COLAB = 'google.colab' in sys.modules",
    'try:',
    '    import google.colab  # noqa: F401',
    '    IN_COLAB = True',
    'except ImportError:',
    '    pass',
    '',
    'REQUIRED = [',
    "    'geopandas',",
    "    'shapely',",
    "    'pyproj',",
    "    'sqlalchemy',",
    "    'pandas',",
    "    'matplotlib',",
    "    'folium',",
    ']',
    '',
    'if IN_COLAB:',
    '    for pkg in REQUIRED:',
    "        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', pkg], check=True)",
    "    print('✅ Packages installed (Colab)')",
    'else:',
    "    print('ℹ️  Running locally — ensure your environment has all required packages.')",
    "    print('   pip install', ' '.join(REQUIRED))",
    '',
    '# Windows users: if pyproj/geopandas fail to import, install via conda:',
    '#   conda install -c conda-forge geopandas pyproj shapely',
)

C = [week_title, learning_objectives, environment]

C.extend([
    md(
        '---',
        '## 📖 Section 1 — Spatial Types and PostGIS Architecture',
        '',
        'PostGIS extends PostgreSQL with spatial types and operators. The core geometry hierarchy starts with single features and grows into multi-part collections.',
        '',
        '| Type | Example WKT | Dimension |',
        '|------|-------------|-----------|',
        '| Point | POINT(4.9 52.3) | 0D |',
        '| LineString | LINESTRING(0 0, 1 1, 2 0) | 1D |',
        '| Polygon | POLYGON((0 0, 1 0, 1 1, 0 1, 0 0)) | 2D |',
        '| MultiPoint | MULTIPOINT(...) | 0D collection |',
        '| MultiPolygon | MULTIPOLYGON(...) | 2D collection |',
        '| GeometryCollection | GEOMETRYCOLLECTION(...) | mixed |',
        '',
        '- **WKT** is readable text, while **WKB** is compact binary for storage and transport.',
        '- **SRID** says which CRS a geometry uses, so metric calculations only make sense in a projected CRS.',
        '- **geometry** is planar and flexible; **geography** is spheroidal and convenient for global distance work.',
        '- The PostGIS catalog view **geometry_columns** exposes registered geometry metadata.',
    ),
    lesson(
        '1.1',
        'Geometry examples from WKT (🔷)',
        'from shapely.geometry import Point, LineString, Polygon',
        'from shapely import wkt',
        '',
        'point = Point(4.895168, 52.370216)',
        'line = LineString([(4.895, 52.370), (4.900, 52.375), (4.910, 52.380)])',
        'poly = Polygon([(4.89, 52.36), (4.92, 52.36), (4.92, 52.38), (4.89, 52.38), (4.89, 52.36)])',
        '',
        'print(f"Point   : {point.wkt}  geom_type={point.geom_type}")',
        'print(f"Line    : length={line.length:.6f} (degrees)")',
        'print(f"Polygon : area={poly.area:.6f} (degrees²)  bounds={poly.bounds}")',
        'print(f"Loaded from WKT: {wkt.loads(\"POINT(4.9 52.37)\").geom_type}")',
    ),
    lesson(
        '1.2',
        'WKT versus WKB round-trip (🔷)',
        'from shapely.geometry import Point, Polygon',
        'from shapely import wkb',
        '',
        'samples = [',
        "    Point(4.9007, 52.3789),",
        "    Polygon([(0, 0), (2, 0), (2, 1), (0, 1), (0, 0)]),",
        ']',
        '',
        'for geom in samples:',
        '    binary = wkb.dumps(geom)',
        '    restored = wkb.loads(binary)',
        '    print(f"{geom.geom_type:<8} | WKT chars={len(geom.wkt):>3} | WKB bytes={len(binary):>3} | equal={restored.equals(geom)}")',
    ),
    lesson(
        '1.3',
        'SRID and geometry catalog quick reference (🔷)',
        'import pandas as pd',
        '',
        'ref = pd.DataFrame(',
        '    [',
        "        ('geometry', 'Planar math in CRS units', 'Most PostGIS analytics'),",
        "        ('geography', 'Spheroidal distance/area on earth', 'Global distance convenience'),",
        "        ('SRID 4326', 'Longitude/latitude in degrees', 'Storage and interchange'),",
        "        ('SRID 28992', 'RD New in metres', 'Dutch metric analysis'),",
        '    ],',
        "    columns=['Concept', 'Meaning', 'Typical use'],",
        ')',
        'print(ref.to_string(index=False))',
    ),
    lesson(
        '1.4',
        'Create table and inspect geometry_columns (🐘)',
        'sql_lines = [',
        '    "CREATE TABLE urban_features (",',
        '    "    id       SERIAL PRIMARY KEY,",',
        '    "    name     TEXT NOT NULL,",',
        '    "    category TEXT,",',
        '    "    geom     geometry(Point, 4326)   -- SRID 4326 = WGS 84",',
        '    ");",',
        '    "",',
        '    "-- Add GiST index",',
        '    "CREATE INDEX urban_features_geom_idx",',
        '    "    ON urban_features",',
        '    "    USING GIST (geom);",',
        '    "",',
        '    "-- Check registered geometry columns",',
        '    "SELECT f_table_name, f_geometry_column, coord_dimension, srid, type",',
        '    "FROM geometry_columns",',
        '    "WHERE f_table_name = \'urban_features\';",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    lesson(
        '1.5',
        'Inspecting geometry dimensions programmatically (🔷)',
        'from shapely.geometry import Point, LineString, Polygon, MultiPoint',
        '',
        'geoms = [',
        "    Point(0, 0),",
        "    LineString([(0, 0), (1, 1)]),",
        "    Polygon([(0, 0), (2, 0), (2, 2), (0, 2), (0, 0)]),",
        "    MultiPoint([(0, 0), (1, 2)]),",
        ']',
        '',
        'for geom in geoms:',
        '    print(f"{geom.geom_type:<12} has area={geom.area:.2f}, length={geom.length:.2f}, bounds={geom.bounds}")',
    ),
    md(
        '### 📖 WKT, WKB, and SRID in practice',
        '',
        '- Use **WKT** for teaching, debugging, and logging because humans can read it.',
        '- Use **WKB** or native database geometry types when performance and compact storage matter.',
        '- Always record the **SRID** explicitly so everyone knows whether units are degrees or metres.',
    ),
    md(
        '---',
        '## 📖 Section 2 — Spatial Indexes and Query Planning',
        '',
        'Spatial indexes make geometry queries practical at city scale. PostGIS usually uses a **GiST** (Generalized Search Tree) index on the geometry column.',
        '',
        '| Strategy | Idea | Performance intuition |',
        '|----------|------|-----------------------|',
        '| Sequential scan | Check every row | O(n), reads the full table |',
        '| GiST index | Bounding-box filter, then exact geometry test | O(log n) style filtering first |',
        '| Rule of thumb | Add GiST to production geometry columns | Faster range, overlap, and distance search |',
        '',
        'The bounding-box operator `&&` is cheap and helps the planner skip most rows before exact predicates like `ST_Intersects` run.',
    ),
    lesson(
        '2.1',
        'Bounding-box overlap intuition (🔷)',
        'from shapely.geometry import Point, box',
        '',
        'a = Point(4.90, 52.37).buffer(0.01)',
        'b = Point(4.93, 52.37).buffer(0.01)',
        'c = Point(5.10, 52.37).buffer(0.01)',
        '',
        'for name, geom in [("A", a), ("B", b), ("C", c)]:',
        '    print(f"{name} bounds = {tuple(round(v, 4) for v in geom.bounds)}")',
        '',
        'print(f"A && B style overlap: {box(*a.bounds).intersects(box(*b.bounds))}")',
        'print(f"A && C style overlap: {box(*a.bounds).intersects(box(*c.bounds))}")',
    ),
    lesson(
        '2.2',
        'Index DDL patterns (🐘)',
        'sql_lines = [',
        '    "-- GiST on geometry column (most common)",',
        '    "CREATE INDEX tbl_geom_idx ON tbl USING GIST(geom);",',
        '    "",',
        '    "-- Partial index: only valid geometries",',
        '    "CREATE INDEX tbl_valid_geom_idx ON tbl USING GIST(geom)",',
        '    "WHERE ST_IsValid(geom);",',
        '    "",',
        '    "-- Composite: geom + category",',
        '    "CREATE INDEX tbl_cat_geom_idx ON tbl (category, ST_XMin(geom::box2d));",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    lesson(
        '2.3',
        'STRtree timing demo (🔷)',
        'import time, random',
        'from shapely.geometry import Point',
        'from shapely.strtree import STRtree',
        '',
        'random.seed(42)',
        'points = [Point(random.uniform(4.8, 5.0), random.uniform(52.3, 52.5)) for _ in range(10_000)]',
        'query = Point(4.9, 52.37).buffer(0.01)',
        '',
        't0 = time.perf_counter()',
        'hits_brute = [p for p in points if p.within(query)]',
        't_brute = time.perf_counter() - t0',
        '',
        'tree = STRtree(points)',
        't0 = time.perf_counter()',
        'hits_tree = list(tree.query(query))',
        't_tree = time.perf_counter() - t0',
        '',
        'print(f"Brute force : {len(hits_brute):4d} hits in {t_brute*1000:.1f} ms")',
        'print(f"STR-tree    : {len(hits_tree):4d} hits in {t_tree*1000:.1f} ms")',
        'print(f"Speedup     : {t_brute/t_tree:.1f}x")',
    ),
    lesson(
        '2.4',
        'Bounding-box prefilter before exact check (🔷)',
        'from shapely.geometry import box',
        '',
        'bbox = box(*query.bounds)',
        'candidates = [p for p in points if box(*p.bounds).intersects(bbox)]',
        'exact_hits = [p for p in candidates if p.within(query)]',
        '',
        'print(f"Total points    : {len(points)}")',
        'print(f"BBox candidates : {len(candidates)}")',
        'print(f"Exact hits      : {len(exact_hits)}")',
        'print(f"False positives after bbox only: {len(candidates) - len(exact_hits)}")',
    ),
    lesson(
        '2.5',
        'Reading a planner mindset (🔷)',
        'import pandas as pd',
        '',
        'planner = pd.DataFrame(',
        '    [',
        "        ('Seq Scan', 'Reads every row', 'Small tables or no useful index'),",
        "        ('Bitmap Index Scan', 'Uses index to collect page hits', 'Many matching rows'),",
        "        ('Index Scan using gist_idx', 'Jumps to relevant geometry ranges', 'Selective spatial predicate'),",
        '    ],',
        "    columns=['Plan node', 'What it means', 'When it appears'],",
        ')',
        'print(planner.to_string(index=False))',
    ),
    md(
        '### 📖 Why every production geometry column deserves GiST',
        '',
        '- Most spatial predicates start with an envelope comparison, so indexes pay off immediately.',
        '- `ST_DWithin` can use the index, while `ST_Distance < N` often has to compute distance for many more rows.',
        '- Create the index early, then validate its effect with `EXPLAIN ANALYZE`.',
    ),
    md(
        '---',
        '## 📖 Section 3 — ST_Intersects and ST_Within',
        '',
        '`ST_Intersects` returns **TRUE** when two geometries share any space. `ST_Within(A, B)` returns **TRUE** when geometry **A** lies entirely inside **B**. `ST_Contains(B, A)` is the inverse relation.',
        '',
        'These predicates are based on the **DE-9IM** spatial relationship model. In practice, think of them as overlap versus containment questions.',
        '',
        '**Diagram description:** imagine two district polygons that do not overlap, plus one point that sits inside Amsterdam and another inside Rotterdam. The point can be within one polygon without the polygons intersecting each other.',
    ),
    lesson(
        '3.1',
        'Predicate demo with polygons and points (🔷)',
        'from shapely.geometry import Point, Polygon',
        '',
        'amsterdam = Polygon([(4.72, 52.27), (5.08, 52.27), (5.08, 52.47), (4.72, 52.47), (4.72, 52.27)])',
        'rotterdam = Polygon([(4.30, 51.85), (4.60, 51.85), (4.60, 52.05), (4.30, 52.05), (4.30, 51.85)])',
        'point_ams = Point(4.9, 52.37)',
        'point_rot = Point(4.47, 51.92)',
        '',
        'print(f"Amsterdam ∩ Rotterdam is empty : {amsterdam.intersection(rotterdam).is_empty}")',
        'print(f"point_ams within Amsterdam     : {point_ams.within(amsterdam)}")',
        'print(f"point_ams within Rotterdam     : {point_ams.within(rotterdam)}")',
        'print(f"Amsterdam contains point_ams   : {amsterdam.contains(point_ams)}")',
        'print(f"Rotterdam contains point_rot   : {rotterdam.contains(point_rot)}")',
    ),
    lesson(
        '3.2',
        'A glimpse at DE-9IM relate strings (🔷)',
        'print(f"point_ams relate Amsterdam : {point_ams.relate(amsterdam)}")',
        'print(f"Amsterdam relate Rotterdam : {amsterdam.relate(rotterdam)}")',
        'print("A T in the pattern usually means a true topological intersection in that position.")',
    ),
    lesson(
        '3.3',
        'PostGIS predicate queries (🐘)',
        'sql_lines = [',
        '    "-- Find all parks that intersect the study area polygon",',
        '    "SELECT p.name, p.category",',
        '    "FROM urban_features p, study_areas s",',
        '    "WHERE s.name = \'City Centre\'",',
        '    "  AND ST_Intersects(p.geom, s.geom);",',
        '    "",',
        '    "-- Points within a district polygon",',
        '    "SELECT f.name",',
        '    "FROM urban_features f",',
        '    "JOIN districts d ON ST_Within(f.geom, d.geom)",',
        '    "WHERE d.name = \'Centrum\';",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    exmd(
        1,
        'Find points within Greater Amsterdam',
        'Given a list of city points and a bounding polygon for Greater Amsterdam, use Shapely to find which points fall within the polygon.',
        [
            'Create a polygon that roughly covers Greater Amsterdam.',
            'Build a small dictionary of named points.',
            'Filter the dictionary to points where `point.within(greater_amsterdam)` is `True`.',
            'Print the matching city names.',
        ],
        "inside = {name: pt for name, pt in city_points.items() if pt.within(greater_amsterdam)}",
    ),
    exstub(
        1,
        [
            'Import Point and Polygon from shapely.geometry.',
            'Create the greater_amsterdam polygon.',
            'Create a city_points dictionary with Amsterdam, Haarlem, Utrecht, and Rotterdam.',
            'Filter for points within the polygon and print the names.',
        ],
    ),
    exsol(
        1,
        'from shapely.geometry import Point, Polygon',
        '',
        'greater_amsterdam = Polygon([',
        '    (4.55, 52.20),',
        '    (5.20, 52.20),',
        '    (5.20, 52.55),',
        '    (4.55, 52.55),',
        '    (4.55, 52.20),',
        '])',
        '',
        'city_points = {',
        "    'Amsterdam': Point(4.8952, 52.3702),",
        "    'Haarlem': Point(4.6462, 52.3874),",
        "    'Utrecht': Point(5.1214, 52.0907),",
        "    'Rotterdam': Point(4.4777, 51.9244),",
        '}',
        '',
        'inside = {name: pt for name, pt in city_points.items() if pt.within(greater_amsterdam)}',
        'print("Cities within Greater Amsterdam:", list(inside.keys()))',
    ),
    md(
        '---',
        '## 📖 Section 4 — ST_Buffer and ST_Area',
        '',
        '`ST_Buffer` grows a geometry by a distance measured in the geometry\'s CRS units. `ST_Area` returns area in CRS units squared.',
        '',
        '**Warning:** buffering in SRID 4326 means buffering in degrees, which distorts shapes and makes areas meaningless. The safe workflow is:',
        '',
        '`ST_Transform` → `ST_Buffer` → `ST_Transform` back',
    ),
    lesson(
        '4.1',
        'Metric buffering in RD New (🔷)',
        'from shapely.geometry import Point',
        'from shapely.ops import transform',
        'from pyproj import Transformer',
        '',
        'point_wgs84 = Point(4.900700, 52.378923)',
        'transformer_to_rd = Transformer.from_crs("EPSG:4326", "EPSG:28992", always_xy=True)',
        'transformer_to_wgs = Transformer.from_crs("EPSG:28992", "EPSG:4326", always_xy=True)',
        '',
        'point_rd = transform(transformer_to_rd.transform, point_wgs84)',
        'buffer_500m = point_rd.buffer(500)',
        'buffer_wgs = transform(transformer_to_wgs.transform, buffer_500m)',
        '',
        'print(f"Point (WGS84)  : {point_wgs84}")',
        'print(f"Point (RD New) : ({point_rd.x:.1f}, {point_rd.y:.1f})")',
        'print(f"Buffer area    : {buffer_500m.area / 1e6:.4f} km²  (expected ~0.785 km²)")',
        'print(f"Buffer bounds (WGS84): {tuple(round(v, 6) for v in buffer_wgs.bounds)}")',
    ),
    lesson(
        '4.2',
        'Why degree buffers are misleading (🔷)',
        'bad_buffer = point_wgs84.buffer(0.005)',
        'good_buffer = buffer_500m',
        '',
        'print(f"Naive degree-buffer area : {bad_buffer.area:.8f} degrees²")',
        'print(f"Projected metric area    : {good_buffer.area:.2f} m²")',
        'print("Interpret degrees as coordinates only, not as metric distance.")',
    ),
    lesson(
        '4.3',
        'PostGIS buffer and area query (🐘)',
        'sql_lines = [',
        '    "-- Buffer in metric CRS, then transform back",',
        '    "SELECT",',
        '    "    name,",',
        '    "    ST_Transform(",',
        '    "        ST_Buffer(",',
        '    "            ST_Transform(geom, 28992),",',
        '    "            500",',
        '    "        ),",',
        '    "        4326",',
        '    "    ) AS buffer_geom,",',
        '    "    ST_Area(ST_Transform(geom, 28992)) AS area_m2",',
        '    "FROM urban_features",',
        '    "WHERE category = \'park\';",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    md(
        '### 📖 Safe pattern for Dutch metric analysis',
        '',
        '- Store raw longitude/latitude in EPSG:4326 when you need interoperability.',
        '- Transform to **EPSG:28992** before measuring distance, area, or buffer size in the Netherlands.',
        '- Transform back to 4326 only for storage or web-map display when needed.',
    ),
    exmd(
        2,
        'Buffer Utrecht Centraal by 1 km',
        'Create a 1 km buffer around Utrecht Centraal (lon=5.1108, lat=52.0894) in RD New, compute its area, and verify it is approximately 3.14 km².',
        [
            'Create the WGS84 point for Utrecht Centraal.',
            'Transform it to EPSG:28992 with PyProj.',
            'Build a 1000-metre buffer.',
            'Print the area in square kilometres.',
        ],
        'area_km2 = buffer_1km.area / 1e6',
    ),
    exstub(
        2,
        [
            'Import Point, transform, and Transformer.',
            'Create the Utrecht Centraal point in WGS84.',
            'Transform to RD New and buffer by 1000 metres.',
            'Print the buffer area in km².',
        ],
    ),
    exsol(
        2,
        'from shapely.geometry import Point',
        'from shapely.ops import transform',
        'from pyproj import Transformer',
        '',
        'utrecht = Point(5.1108, 52.0894)',
        'to_rd = Transformer.from_crs("EPSG:4326", "EPSG:28992", always_xy=True)',
        'utrecht_rd = transform(to_rd.transform, utrecht)',
        'buffer_1km = utrecht_rd.buffer(1000)',
        'area_km2 = buffer_1km.area / 1e6',
        '',
        'print(f"Area: {area_km2:.3f} km²")',
        'print("Close to π × 1² ≈ 3.142 km²")',
    ),
    md(
        '---',
        '## 📖 Section 5 — ST_DWithin — Distance Queries',
        '',
        '`ST_DWithin(A, B, distance)` returns **TRUE** when two geometries are within a threshold distance of each other. In PostGIS this is usually faster than `ST_Distance(A, B) < N` because the planner can use the spatial index first.',
        '',
        'Use `ST_DWithin` to pre-filter candidates, then compute `ST_Distance` only for the smaller result set you want to rank or display.',
    ),
    lesson(
        '5.1',
        'Approximate distance in Shapely (🔷)',
        'from shapely.geometry import Point',
        '',
        'centraal = Point(4.900700, 52.378923)',
        'vondelpark = Point(4.870079, 52.358560)',
        '',
        'dist_deg = centraal.distance(vondelpark)',
        'dist_m = dist_deg * 111_000',
        '',
        'print(f"Distance (degrees)  : {dist_deg:.6f}")',
        'print(f"Distance (approx m) : {dist_m:.0f} m  (actual ~3.1 km)")',
        '',
        'try:',
        '    from shapely import dwithin',
        '    print(f"Within 5 km (0.045°): {dwithin(centraal, vondelpark, 0.045)}")',
        'except ImportError:',
        '    print(f"Within 0.045° buffer: {centraal.distance(vondelpark) <= 0.045}")',
    ),
    lesson(
        '5.2',
        'Candidate filtering before exact ranking (🔷)',
        'landmarks = {',
        "    'Centraal': centraal,",
        "    'Vondelpark': vondelpark,",
        "    'Rijksmuseum': Point(4.8852, 52.3600),",
        "    'Keukenhof': Point(4.5468, 52.2699),",
        '}',
        '',
        'radius_deg = 0.03',
        'candidates = {name: pt for name, pt in landmarks.items() if pt.distance(centraal) <= radius_deg}',
        'ranked = sorted(((name, centraal.distance(pt) * 111_000) for name, pt in candidates.items()), key=lambda x: x[1])',
        '',
        'print(f"Candidates within {radius_deg:.3f}°:")',
        'for name, dist_m in ranked:',
        '    print(f"  {name:<12} ~ {dist_m:6.0f} m")',
    ),
    lesson(
        '5.3',
        'Index-aware PostGIS distance query (🐘)',
        'sql_lines = [',
        '    "-- Find all features within 500 m of Amsterdam Centraal",',
        '    "-- ST_DWithin uses the GiST index automatically",',
        '    "SELECT",',
        '    "    f.name,",',
        '    "    f.category,",',
        '    "    ST_Distance(",',
        '    "        ST_Transform(f.geom, 28992),",',
        '    "        ST_Transform(ST_SetSRID(ST_MakePoint(4.9007, 52.3789), 4326), 28992)",',
        '    "    ) AS dist_m",',
        '    "FROM urban_features f",',
        '    "WHERE ST_DWithin(",',
        '    "    ST_Transform(f.geom, 28992),",',
        '    "    ST_Transform(ST_SetSRID(ST_MakePoint(4.9007, 52.3789), 4326), 28992),",',
        '    "    500",',
        '    ")",',
        '    "ORDER BY dist_m;",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    md(
        '### 📖 Performance tip',
        '',
        '- Use `ST_DWithin` in the `WHERE` clause to narrow candidates with the GiST index.',
        '- Add `ST_Distance` in the `SELECT` list only when you actually need the measured output.',
        '- In Python demos with longitude/latitude, distance is approximate unless you reproject first.',
    ),
    exmd(
        3,
        'Find points within 2 km of the Rijksmuseum',
        'Using Shapely, find all points from a sample list that are within 2 km of the Rijksmuseum (lon=4.8852, lat=52.3600). Use the 1° ≈ 111,000 m approximation.',
        [
            'Create the Rijksmuseum point.',
            'Create a dictionary of sample points.',
            'Compute distances in degrees and convert to metres.',
            'Print points whose approximate distance is <= 2000 m.',
        ],
        'nearby = [name for name, pt in points.items() if museum.distance(pt) * 111_000 <= 2000]',
    ),
    exstub(
        3,
        [
            'Create the Rijksmuseum point.',
            'Create sample points such as Centraal, Vondelpark, and Utrecht Dom.',
            'Filter to points within 2000 metres.',
            'Print the names and approximate distances.',
        ],
    ),
    exsol(
        3,
        'from shapely.geometry import Point',
        '',
        'museum = Point(4.8852, 52.3600)',
        'points = {',
        "    'Amsterdam Centraal': Point(4.9007, 52.3789),",
        "    'Vondelpark': Point(4.8701, 52.3583),",
        "    'Utrecht Dom': Point(5.1214, 52.0907),",
        "    'Keukenhof': Point(4.5468, 52.2699),",
        '}',
        '',
        'for name, pt in points.items():',
        '    dist_m = museum.distance(pt) * 111_000',
        '    if dist_m <= 2000:',
        '        print(f"{name:<18} ~ {dist_m:6.0f} m")',
    ),
    md(
        '---',
        '## 📖 Section 6 — ST_Transform — Coordinate Reference Systems',
        '',
        'Spatial analysis only makes sense when you know the CRS and units. `ST_Transform` reprojects coordinates between SRIDs so storage and analysis can each use the right system.',
        '',
        '| SRID | Name | Unit | Use case |',
        '|------|------|------|---------|',
        '| 4326 | WGS 84 | degrees | GPS, global data storage |',
        '| 28992 | RD New | metres | Netherlands national CRS |',
        '| 3857 | Web Mercator | metres | Tile maps, web mapping |',
        '| 32631 | UTM Zone 31N | metres | Central Europe metric |',
    ),
    lesson(
        '6.1',
        'Batch transform Dutch cities (🔷)',
        'from pyproj import Transformer, CRS',
        '',
        'crs_wgs = CRS.from_epsg(4326)',
        'crs_rd = CRS.from_epsg(28992)',
        'crs_merc = CRS.from_epsg(3857)',
        '',
        'cities = {',
        "    'Amsterdam': (4.8952, 52.3702),",
        "    'Rotterdam': (4.4777, 51.9244),",
        "    'Utrecht': (5.1214, 52.0907),",
        '}',
        '',
        'to_rd = Transformer.from_crs(4326, 28992, always_xy=True)',
        'to_merc = Transformer.from_crs(4326, 3857, always_xy=True)',
        '',
        'print(f"{\'City\':<12}  {\'WGS84 (lon,lat)\':<26}  {\'RD New (x,y)\':<24}  {\'WebMercator (x,y)\'}")',
        'print("-" * 100)',
        'for city, (lon, lat) in cities.items():',
        '    rx, ry = to_rd.transform(lon, lat)',
        '    mx, my = to_merc.transform(lon, lat)',
        '    print(f"{city:<12}  ({lon:.4f}, {lat:.4f})          ({rx:,.0f}, {ry:,.0f})      ({mx:,.0f}, {my:,.0f})")',
    ),
    lesson(
        '6.2',
        'Round-trip transform accuracy check (🔷)',
        'back_to_wgs = Transformer.from_crs(28992, 4326, always_xy=True)',
        'lon, lat = cities["Amsterdam"]',
        'rx, ry = to_rd.transform(lon, lat)',
        'lon2, lat2 = back_to_wgs.transform(rx, ry)',
        '',
        'print(f"Original     : ({lon:.6f}, {lat:.6f})")',
        'print(f"Round-tripped: ({lon2:.6f}, {lat2:.6f})")',
        'print(f"Difference   : ({abs(lon - lon2):.8f}, {abs(lat - lat2):.8f})")',
    ),
    lesson(
        '6.3',
        'PostGIS ST_Transform query (🐘)',
        'sql_lines = [',
        '    "-- ST_Transform to reproject geometry",',
        '    "SELECT",',
        '    "    name,",',
        '    "    ST_AsText(geom) AS wgs84_wkt,",',
        '    "    ST_AsText(ST_Transform(geom, 28992)) AS rd_wkt,",',
        '    "    ST_X(ST_Transform(geom, 28992)) AS rd_x,",',
        '    "    ST_Y(ST_Transform(geom, 28992)) AS rd_y",',
        '    "FROM urban_features",',
        '    "WHERE category = \'station\'",',
        '    "ORDER BY name;",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    md(
        '### 📖 CRS decision rule',
        '',
        '- Keep **4326** for interoperability and incoming GPS-style data.',
        '- Switch to **28992** when you need Dutch metric accuracy for distance, area, and buffering.',
        '- Use **3857** for display on slippy maps, not for authoritative measurement.',
    ),
    exmd(
        4,
        'Transform the Netherlands bounding box',
        'Use PyProj to transform the corners of the Netherlands bounding box (3.36, 50.75) to (7.23, 53.55) from WGS84 to RD New, and print the resulting rectangle in metres.',
        [
            'Create a transformer from EPSG:4326 to EPSG:28992.',
            'Transform the southwest and northeast corners.',
            'Print the transformed coordinates.',
            'Compute approximate width and height in metres.',
        ],
        '(x1, y1), (x2, y2) = to_rd.transform(3.36, 50.75), to_rd.transform(7.23, 53.55)',
    ),
    exstub(
        4,
        [
            'Create the 4326 → 28992 transformer.',
            'Transform the southwest corner (3.36, 50.75).',
            'Transform the northeast corner (7.23, 53.55).',
            'Print the rectangle width and height in metres.',
        ],
    ),
    exsol(
        4,
        'from pyproj import Transformer',
        '',
        'to_rd = Transformer.from_crs(4326, 28992, always_xy=True)',
        'x1, y1 = to_rd.transform(3.36, 50.75)',
        'x2, y2 = to_rd.transform(7.23, 53.55)',
        '',
        'print(f"SW corner: ({x1:,.0f}, {y1:,.0f})")',
        'print(f"NE corner: ({x2:,.0f}, {y2:,.0f})")',
        'print(f"Width   : {abs(x2 - x1):,.0f} m")',
        'print(f"Height  : {abs(y2 - y1):,.0f} m")',
    ),
    md(
        '---',
        '## 📖 Section 7 — Combining Spatial Functions',
        '',
        'PostGIS spatial functions behave a lot like set algebra. You can combine them to answer richer planning questions in one query.',
        '',
        '- `ST_Intersection` keeps the shared part.',
        '- `ST_Union` merges both geometries.',
        '- `ST_Difference` keeps only what is unique to the first geometry.',
        '- `ST_SymDifference` keeps everything not shared.',
        '',
        'Always remember that some overlays can produce **empty geometries** or `NULL`-like results that need handling in downstream logic.',
    ),
    lesson(
        '7.1',
        'Set operations with Shapely (🔷)',
        'from shapely.geometry import Polygon',
        '',
        'district_a = Polygon([(0, 0), (2, 0), (2, 2), (0, 2), (0, 0)])',
        'district_b = Polygon([(1, 0), (3, 0), (3, 2), (1, 2), (1, 0)])',
        '',
        'inter = district_a.intersection(district_b)',
        'union = district_a.union(district_b)',
        'diff = district_a.difference(district_b)',
        'sym = district_a.symmetric_difference(district_b)',
        '',
        'print(f"Intersection area : {inter.area:.2f}  (overlap zone)")',
        'print(f"Union area        : {union.area:.2f}  (combined)")',
        'print(f"Difference A-B    : {diff.area:.2f}  (only in A)")',
        'print(f"Symmetric diff    : {sym.area:.2f}  (not shared)")',
        'print(f"Inter + Diff = A  : {inter.area + diff.area:.2f} == {district_a.area:.2f}")',
    ),
    lesson(
        '7.2',
        'Chaining buffer and intersection (🔷)',
        'station_zone = Polygon([(0.8, 0.8), (2.2, 0.8), (2.2, 2.2), (0.8, 2.2), (0.8, 0.8)])',
        'park_core = Polygon([(1.4, 0.5), (2.6, 0.5), (2.6, 2.5), (1.4, 2.5), (1.4, 0.5)])',
        'buffered_zone = station_zone.buffer(0.2)',
        'service_area = buffered_zone.intersection(park_core)',
        '',
        'print(f"Buffered station zone area : {buffered_zone.area:.2f}")',
        'print(f"Shared service area        : {service_area.area:.2f}")',
        'print(f"Service area empty?        : {service_area.is_empty}")',
    ),
    lesson(
        '7.3',
        'PostGIS overlay query (🐘)',
        'sql_lines = [',
        '    "-- Areas of two districts that overlap",',
        '    "SELECT",',
        '    "    a.name AS district_a,",',
        '    "    b.name AS district_b,",',
        '    "    ST_Area(ST_Intersection(a.geom, b.geom)) AS overlap_m2,",',
        '    "    ST_Area(ST_Union(a.geom, b.geom)) AS combined_m2,",',
        '    "    ST_AsText(ST_Intersection(a.geom, b.geom)) AS overlap_wkt",',
        '    "FROM districts a",',
        '    "JOIN districts b ON a.id < b.id",',
        '    "WHERE ST_Intersects(a.geom, b.geom);",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    lesson(
        '7.4',
        'Defensive handling for empty results (🔷)',
        'pairs = [',
        '    ("overlap", district_a, district_b),',
        '    ("disjoint", district_a, Polygon([(5, 5), (6, 5), (6, 6), (5, 6), (5, 5)])),',
        ']',
        '',
        'for label, left, right in pairs:',
        '    result = left.intersection(right)',
        '    area = 0.0 if result.is_empty else result.area',
        '    print(f"{label:<8} -> empty={result.is_empty}, area={area:.2f}")',
    ),
    lesson(
        '7.5',
        'Mini workflow: difference after shared area removal (🔷)',
        'remaining_a = district_a.difference(inter)',
        'remaining_b = district_b.difference(inter)',
        'print(f"Remaining A area: {remaining_a.area:.2f}")',
        'print(f"Remaining B area: {remaining_b.area:.2f}")',
        'print(f"Pieces still sum to union? {(remaining_a.area + remaining_b.area + inter.area):.2f} == {union.area:.2f}")',
    ),
    md(
        '---',
        '## 📖 Section 8 — Running PostGIS Queries from Python',
        '',
        'There are three common integration patterns from Python into PostGIS:',
        '',
        '1. **SQLAlchemy `text()`** — raw SQL with parameters and transaction control.',
        '2. **GeoPandas `read_postgis()`** — directly returns a GeoDataFrame.',
        '3. **psycopg2 cursor** — lower-level control and manual WKB handling when needed.',
        '',
        '| Pattern | Best for | Trade-off |',
        '|---------|----------|-----------|',
        '| SQLAlchemy text() | Controlled SQL and parameter binding | You parse or wrap results yourself |',
        '| gpd.read_postgis() | Analysis notebooks and mapping | Requires a live PostGIS connection |',
        '| psycopg2 cursor | Low-level ETL or custom drivers | More boilerplate |',
        '',
        '**Decision guide:**',
        '- Use **SQLAlchemy `text()`** when you want explicit SQL, named parameters, and transaction control.',
        '- Use **GeoPandas `read_postgis()`** when the end goal is mapping, plotting, joins, or notebook inspection.',
        '- Use **psycopg2** when you need lower-level cursor features, server-side COPY, or custom binary handling.',
        '',
        '**Parameterization checklist:**',
        '- Keep geometry creation inside SQL with functions like `ST_MakePoint` or send WKT/WKB as parameters.',
        '- Avoid string interpolation for filters or coordinates; bind them as parameters instead.',
        '- Pull only the columns and rows you actually need so Python receives a smaller result set.',
    ),
    lesson(
        '8.1',
        'Parameterized SQL with SQLAlchemy text() (🔷)',
        'from sqlalchemy import create_engine, text',
        '',
        'preview_engine = create_engine("sqlite+pysqlite:///:memory:", echo=False)',
        'with preview_engine.connect() as conn:',
        '    row = conn.execute(text("SELECT :city AS city, :category AS category"), {"city": "Amsterdam", "category": "station"}).mappings().one()',
        'print(dict(row))',
    ),
    lesson(
        '8.2',
        'SQLite + Shapely + GeoDataFrame demo (🔷)',
        'import pandas as pd',
        'import geopandas as gpd',
        'from shapely.geometry import Point',
        'from shapely import wkt as shapely_wkt',
        'from sqlalchemy import create_engine, text',
        'from pathlib import Path',
        '',
        "DATA_DIR = Path.home() / '.geospatial_course' / 'week07'",
        'DATA_DIR.mkdir(parents=True, exist_ok=True)',
        "DB_PATH = DATA_DIR / 'week07_demo.db'",
        "engine = create_engine(f'sqlite:///{DB_PATH}', echo=False)",
        '',
        'create_sql = "\\n".join([',
        '    "CREATE TABLE urban_features (",',
        '    "    id INTEGER PRIMARY KEY AUTOINCREMENT,",',
        '    "    name TEXT NOT NULL,",',
        '    "    category TEXT,",',
        '    "    geom_wkt TEXT",',
        '    ")",',
        '])',
        'insert_sql = "\\n".join([',
        '    "INSERT INTO urban_features (name, category, geom_wkt) VALUES",',
        '    "(\'Amsterdam Centraal\', \'station\',  \'POINT(4.9007 52.3789)\'),",',
        '    "(\'Vondelpark\',         \'park\',     \'POINT(4.8701 52.3583)\'),",',
        '    "(\'Rijksmuseum\',        \'museum\',   \'POINT(4.8852 52.3600)\'),",',
        '    "(\'Rotterdam Centraal\', \'station\',  \'POINT(4.4663 51.9225)\'),",',
        '    "(\'Keukenhof\',          \'park\',     \'POINT(4.5468 52.2699)\'),",',
        '    "(\'Utrecht Dom\',        \'monument\', \'POINT(5.1214 52.0907)\')",',
        '])',
        '',
        'with engine.begin() as conn:',
        "    conn.execute(text('DROP TABLE IF EXISTS urban_features'))",
        '    conn.execute(text(create_sql))',
        '    conn.execute(text(insert_sql))',
        '',
        'with engine.connect() as conn:',
        "    rows = pd.read_sql(text('SELECT id, name, category, geom_wkt FROM urban_features'), conn)",
        '',
        "rows['geometry'] = rows['geom_wkt'].apply(shapely_wkt.loads)",
        "gdf = gpd.GeoDataFrame(rows, geometry='geometry', crs='EPSG:4326')",
        '',
        "print(gdf[['name', 'category', 'geometry']].to_string(index=False))",
        'print(f"\\nCRS: {gdf.crs}  |  {len(gdf)} features")',
    ),
    lesson(
        '8.3',
        'Summarise query results after loading (🔷)',
        'category_summary = gdf.groupby("category").size().rename("feature_count")',
        'print(category_summary.to_string())',
        'print(f"\\nUnique categories: {gdf[\'category\'].nunique()}")',
    ),
    lesson(
        '8.4',
        'GeoPandas read_postgis pattern (🐘)',
        'code_lines = [',
        '    "import geopandas as gpd",',
        '    "",',
        '    "CONN_STR = \'postgresql://user:password@localhost:5432/geobase\'",',
        '    "sql = \'\\n\'.join([",',
        '    "    \'SELECT id, name, category, geom\',",',
        '    "    \'FROM urban_features\',",',
        '    "    \'WHERE ST_DWithin(\',",',
        '    "    \'    ST_Transform(geom, 28992),\',",',
        '    "    \'    ST_Transform(ST_SetSRID(ST_MakePoint(4.9007, 52.3789), 4326), 28992),\',",',
        '    "    \'    2000\',",',
        '    "    \')\',",',
        '    "])",',
        '    "gdf = gpd.read_postgis(",',
        '    "    sql=sql,",',
        '    "    con=CONN_STR,",',
        '    "    geom_col=\'geom\',",',
        '    "    crs=\'EPSG:4326\',",',
        '    ")",',
        '    "print(gdf.head())",',
        ']',
        'print("\\n".join(code_lines))',
    ),
    md(
        '### 📖 Python integration best practice',
        '',
        '- Use parameter binding with `text()` instead of string concatenation for safety.',
        '- Keep SQL logic in SQL when the database can do the work faster.',
        '- Convert to GeoDataFrames when you want plotting, joins, or notebook-friendly inspection.',
    ),
    exmd(
        5,
        'Filter the demo GeoDataFrame near Amsterdam Centraal',
        'Using the demo SQLite GeoDataFrame from 8.2, filter features within 0.05 degrees of Amsterdam Centraal using Shapely `.within()` on a buffer. Print the results.',
        [
            'Locate the Amsterdam Centraal point from `gdf`.',
            'Create a 0.05-degree buffer around it.',
            'Filter rows whose geometry falls within that buffer.',
            'Print name, category, and approximate degree distance.',
        ],
        'near = gdf[gdf.geometry.within(anchor.buffer(0.05))].copy()',
    ),
    exstub(
        5,
        [
            'Assume gdf already exists from Section 8.2.',
            'Get the Amsterdam Centraal anchor geometry.',
            'Create a 0.05-degree buffer around the anchor.',
            'Filter and print the nearby features.',
        ],
    ),
    exsol(
        5,
        'if "gdf" not in globals():',
        '    raise NameError("Run Section 8.2 first so gdf exists.")',
        '',
        'anchor = gdf.loc[gdf["name"] == "Amsterdam Centraal", "geometry"].iloc[0]',
        'near = gdf[gdf.geometry.within(anchor.buffer(0.05))].copy()',
        'near["dist_deg"] = near.geometry.distance(anchor)',
        'print(near[["name", "category", "dist_deg"]].sort_values("dist_deg").to_string(index=False))',
    ),
    md(
        '---',
        '## 📖 Section 9 — EXPLAIN ANALYZE and Performance',
        '',
        '`EXPLAIN ANALYZE` shows PostgreSQL\'s estimated plan and the actual runtime. For spatial work, the key question is simple: **did the planner use the GiST index or fall back to a sequential scan?**',
        '',
        'Important fields:',
        '- **cost**: planner estimate of work',
        '- **rows**: estimated row count',
        '- **width**: estimated bytes per row',
        '- **actual time**: measured runtime',
        '- **loops**: how many times the node executed',
        '',
        '**Fast reading pattern for spatial plans:**',
        '1. Find the top-most scan node and check whether it says `Seq Scan`, `Bitmap Heap Scan`, or `Index Scan`.',
        '2. Look for the geometry predicate and confirm whether the planner can use the GiST index before exact evaluation.',
        '3. Compare `rows` versus `actual rows` to see whether estimates are realistic.',
        '4. Compare total runtime before and after adding the index or rewriting the predicate.',
        '',
        'A good spatial tuning habit is to save the before/after plan text whenever you change an index, CRS transform strategy, or distance predicate.',
    ),
    lesson(
        '9.1',
        'Plan anatomy quick reference (🔷)',
        'import pandas as pd',
        '',
        'plan_terms = pd.DataFrame(',
        '    [',
        "        ('Seq Scan', 'Reads every row in the table', 'Usually a warning sign on large spatial tables'),",
        "        ('Index Scan using gist_idx', 'Uses the geometry index directly', 'Good for selective predicates'),",
        "        ('Bitmap Heap Scan', 'Collects many index matches then fetches pages', 'Often appears for medium selectivity'),",
        "        ('actual time', 'Measured runtime', 'Confirms whether the plan was truly fast'),",
        '    ],',
        "    columns=['Term', 'Meaning', 'What to look for'],",
        ')',
        'print(plan_terms.to_string(index=False))',
    ),
    lesson(
        '9.2',
        'PostGIS EXPLAIN patterns (🐘)',
        'sql_lines = [',
        '    "-- Check if spatial index is being used",',
        '    "EXPLAIN ANALYZE",',
        '    "SELECT name",',
        '    "FROM urban_features",',
        '    "WHERE ST_DWithin(",',
        '    "    ST_Transform(geom, 28992),",',
        '    "    ST_Transform(ST_SetSRID(ST_MakePoint(4.9007, 52.3789), 4326), 28992),",',
        '    "    500",',
        '    ");",',
        '    "",',
        '    "-- Force sequential scan to compare",',
        '    "SET enable_indexscan = off;",',
        '    "EXPLAIN ANALYZE",',
        '    "SELECT name FROM urban_features",',
        '    "WHERE ST_DWithin(...);",',
        '    "SET enable_indexscan = on;",',
        ']',
        'print("\\n".join(sql_lines))',
    ),
    lesson(
        '9.3',
        'Brute-force versus STRtree timing with notebook data (🔷)',
        'import time',
        'from shapely.geometry import Point',
        'from shapely.strtree import STRtree',
        '',
        'if "gdf" not in globals():',
        '    raise NameError("Run Section 8.2 first so gdf exists.")',
        '',
        'ref_point = Point(4.9007, 52.3789)',
        'radius = 0.05',
        '',
        't0 = time.perf_counter()',
        'results_bf = gdf[gdf.geometry.apply(lambda g: g.distance(ref_point) <= radius)]',
        't_bf = time.perf_counter() - t0',
        '',
        'tree = STRtree(gdf.geometry.values)',
        'query_geom = ref_point.buffer(radius)',
        't0 = time.perf_counter()',
        'idx = tree.query(query_geom)',
        't_tree = time.perf_counter() - t0',
        '',
        'print(f"Brute force  : {len(results_bf)} hits in {t_bf*1000:.2f} ms")',
        'print(f"STRtree      : {len(idx)} hits in {t_tree*1000:.2f} ms")',
        'print("\\nIn PostGIS: equivalent speedup happens with GiST index on geom column.")',
    ),
    lesson(
        '9.4',
        'Compare fake plans before and after GiST (🔷)',
        'plans = pd.DataFrame(',
        '    [',
        "        ('Before index', 'Seq Scan on urban_features', 150000, 820.4),",
        "        ('After index', 'Index Scan using urban_features_geom_idx', 1200, 18.7),",
        '    ],',
        "    columns=['Scenario', 'Dominant node', 'Rows checked', 'Actual time (ms)'],",
        ')',
        'print(plans.to_string(index=False))',
    ),
    lesson(
        '9.5',
        'Spatial performance checklist (🔷)',
        'checks = [',
        '    "Do geometry columns have a GiST index?",',
        '    "Are metric calculations done in a projected CRS?",',
        '    "Can ST_DWithin replace ST_Distance < N in WHERE?",',
        '    "Did EXPLAIN ANALYZE switch from Seq Scan to Index Scan?",',
        ']',
        'for i, check in enumerate(checks, start=1):',
        '    print(f"{i}. {check}")',
    ),
    md(
        '### 📖 What to compare before and after indexing',
        '',
        '- The node type should move from `Seq Scan` toward `Index Scan` or `Bitmap Index Scan`.',
        '- The number of rows visited should drop sharply.',
        '- Actual time matters more than estimated cost when you validate improvements.',
    ),
    md(
        '## 🔬 Mini-Lab — Urban Planning Questions',
        '',
        '**Scenario:** You are a spatial analyst at a Dutch municipality. Using the urban features ',
        'dataset, answer the following planning questions using PostGIS-style spatial analysis ',
        '(demonstrated with Shapely on the demo dataset).',
        '',
        '**Dataset:** 6 urban features (stations, parks, museums, monument) loaded in Section 8.',
    ),
    labstep(
        1,
        'Setup and reload the demo GeoDataFrame',
        'import pandas as pd',
        'import geopandas as gpd',
        'from shapely import wkt as shapely_wkt',
        'from sqlalchemy import create_engine, text',
        'from pathlib import Path',
        '',
        "DATA_DIR = Path.home() / '.geospatial_course' / 'week07'",
        'DATA_DIR.mkdir(parents=True, exist_ok=True)',
        "DB_PATH = DATA_DIR / 'week07_demo.db'",
        "engine = create_engine(f'sqlite:///{DB_PATH}', echo=False)",
        '',
        'create_sql = "\\n".join([',
        '    "CREATE TABLE IF NOT EXISTS urban_features (",',
        '    "    id INTEGER PRIMARY KEY AUTOINCREMENT,",',
        '    "    name TEXT NOT NULL,",',
        '    "    category TEXT,",',
        '    "    geom_wkt TEXT",',
        '    ")",',
        '])',
        'insert_sql = "\\n".join([',
        '    "INSERT INTO urban_features (name, category, geom_wkt) VALUES",',
        '    "(\'Amsterdam Centraal\', \'station\',  \'POINT(4.9007 52.3789)\'),",',
        '    "(\'Vondelpark\',         \'park\',     \'POINT(4.8701 52.3583)\'),",',
        '    "(\'Rijksmuseum\',        \'museum\',   \'POINT(4.8852 52.3600)\'),",',
        '    "(\'Rotterdam Centraal\', \'station\',  \'POINT(4.4663 51.9225)\'),",',
        '    "(\'Keukenhof\',          \'park\',     \'POINT(4.5468 52.2699)\'),",',
        '    "(\'Utrecht Dom\',        \'monument\', \'POINT(5.1214 52.0907)\')",',
        '])',
        '',
        'with engine.begin() as conn:',
        '    conn.execute(text(create_sql))',
        '    count = conn.execute(text("SELECT COUNT(*) FROM urban_features")).scalar_one()',
        '    if count == 0:',
        '        conn.execute(text(insert_sql))',
        '',
        'with engine.connect() as conn:',
        "    rows = pd.read_sql(text('SELECT id, name, category, geom_wkt FROM urban_features'), conn)",
        '',
        "rows['geometry'] = rows['geom_wkt'].apply(shapely_wkt.loads)",
        "gdf = gpd.GeoDataFrame(rows, geometry='geometry', crs='EPSG:4326')",
        'print(gdf[["name", "category"]].to_string(index=False))',
        'print(f"\\nLoaded {len(gdf)} features from {DB_PATH}")',
    ),
    labstep(
        2,
        'Buffer Amsterdam Centraal by 3 km and list nearby features',
        'anchor = gdf.loc[gdf["name"] == "Amsterdam Centraal", "geometry"].iloc[0]',
        'buffer_deg = anchor.buffer(0.027)',
        'nearby = gdf[gdf.geometry.within(buffer_deg)].copy()',
        'nearby["distance_km_approx"] = nearby.geometry.distance(anchor) * 111',
        'nearby = nearby[["name", "category", "distance_km_approx"]].sort_values("distance_km_approx")',
        'print(nearby.to_string(index=False, formatters={"distance_km_approx": lambda v: f"{v:.2f}"}))',
    ),
    labstep(
        3,
        'Classify each feature as North, South, or Border',
        'from shapely.geometry import Polygon',
        '',
        'north_bbox = Polygon([(3.0, 52.05), (7.5, 52.05), (7.5, 53.8), (3.0, 53.8), (3.0, 52.05)])',
        'south_bbox = Polygon([(3.0, 50.5), (7.5, 50.5), (7.5, 52.15), (3.0, 52.15), (3.0, 50.5)])',
        '',
        'def classify_region(pt):',
        '    in_north = pt.within(north_bbox)',
        '    in_south = pt.within(south_bbox)',
        '    if in_north and in_south:',
        '        return "Border"',
        '    if in_north:',
        '        return "North"',
        '    if in_south:',
        '        return "South"',
        '    return "Outside"',
        '',
        'gdf["region_class"] = gdf.geometry.apply(classify_region)',
        'print(gdf[["name", "region_class"]].to_string(index=False))',
    ),
    labstep(
        4,
        'Compute a distance matrix in approximate kilometres',
        'import pandas as pd',
        '',
        'names = gdf["name"].tolist()',
        'matrix = pd.DataFrame(index=names, columns=names, dtype=float)',
        'for name_i, geom_i in zip(gdf["name"], gdf.geometry):',
        '    for name_j, geom_j in zip(gdf["name"], gdf.geometry):',
        '        matrix.loc[name_i, name_j] = geom_i.distance(geom_j) * 111',
        'print(matrix.round(2).to_string())',
    ),
    labstep(
        5,
        'Transform all features to RD New and compare coordinates',
        'from pyproj import Transformer',
        '',
        'to_rd = Transformer.from_crs(4326, 28992, always_xy=True)',
        'gdf_rd = gdf.to_crs(28992)',
        'coord_table = pd.DataFrame({',
        '    "name": gdf["name"],',
        '    "lon": gdf.geometry.x.round(4),',
        '    "lat": gdf.geometry.y.round(4),',
        '    "rd_x": gdf_rd.geometry.x.round(0).astype(int),',
        '    "rd_y": gdf_rd.geometry.y.round(0).astype(int),',
        '})',
        'print(coord_table.to_string(index=False))',
    ),
    labstep(
        6,
        'Export RD New features to GeoJSON',
        'if "gdf_rd" not in globals():',
        '    gdf_rd = gdf.to_crs(28992)',
        '',
        "out_geojson = DATA_DIR / 'urban_features_rd.geojson'",
        'gdf_rd.to_file(out_geojson, driver="GeoJSON")',
        'size_kb = out_geojson.stat().st_size / 1024',
        'print(f"Exported: {out_geojson}")',
        'print(f"File size: {size_kb:.1f} KB")',
    ),
    md(
        '## 🏁 Week 7 Summary',
        '',
        "Congratulations — you've mastered the PostGIS core query toolkit!",
        '',
        '| Section | Key Concept |',
        '|---------|-------------|',
        '| 1 | Geometry types: Point, LineString, Polygon + WKT/WKB/SRID |',
        '| 2 | GiST spatial indexes: O(log n) bounding-box filtering |',
        '| 3 | ST_Intersects (shared space) vs ST_Within (containment) |',
        '| 4 | ST_Buffer (metric CRS!) + ST_Area for area measurement |',
        '| 5 | ST_DWithin for index-aware distance queries |',
        '| 6 | ST_Transform: always reproject before metric calculations |',
        '| 7 | Set algebra: Intersection, Union, Difference, SymDifference |',
        '| 8 | Python integration: SQLAlchemy text() + gpd.read_postgis() |',
        '| 9 | EXPLAIN ANALYZE: diagnose Seq Scan vs Index Scan |',
        '| 10 | Mini-Lab: buffer, classify, distance matrix, export |',
        '',
        '### ☑️ Self-assessment checklist',
        '- [ ] I can explain the difference between ST_Intersects and ST_Within',
        '- [ ] I know why to use ST_Transform before ST_Buffer for metric results',
        '- [ ] I can write ST_DWithin queries that use the GiST index',
        '- [ ] I understand how to read EXPLAIN ANALYZE output for spatial queries',
        '- [ ] I can run PostGIS SQL from Python with SQLAlchemy and GeoPandas',
        '- [ ] I can create a Shapely STRtree and explain why it\'s faster for point-in-polygon',
        '- [ ] I know the difference between WGS84, RD New, and Web Mercator',
        '- [ ] I can compute a distance matrix with Shapely and export to GeoJSON',
        '- [ ] I can combine ST_Intersects + ST_Buffer + ST_Transform in one SELECT',
        '- [ ] I am ready to tackle advanced spatial analytics in Week 8',
        '',
        '## 📚 Week 8 Preview',
        '',
        '| Topic | What you\'ll learn |',
        '|-------|-------------------|',
        '| Spatial joins at scale | JOIN ON ST_Intersects with LATERAL and index hints |',
        '| Nearest-neighbour queries | KNN with <-> operator and ST_DWithin |',
        '| Geometry validity | ST_IsValid, ST_MakeValid, ST_Buffer(0) repair trick |',
        '| Performance tuning | VACUUM ANALYZE, partial indexes, clustering by geom |',
        '| Aggregation | ST_Union, ST_Collect, ST_ConvexHull for dissolve operations |',
        '',
        '## 🧠 PostGIS phrasebook',
        '',
        '| Need | Common pattern | Why it matters |',
        '|------|----------------|----------------|',
        '| Find overlap | `ST_Intersects(a.geom, b.geom)` | Fast yes/no topological filter |',
        '| Test containment | `ST_Within(a.geom, b.geom)` | Point-in-polygon and zoning checks |',
        '| Make metric buffer | `ST_Buffer(ST_Transform(geom, 28992), 500)` | Correct metre-based analysis |',
        '| Measure area | `ST_Area(ST_Transform(geom, 28992))` | Real square-metre output |',
        '| Search nearby | `ST_DWithin(..., distance)` | Index-aware distance filtering |',
        '| Reproject | `ST_Transform(geom, target_srid)` | Switch storage CRS to analysis CRS |',
        '| Clip features | `ST_Intersection(a.geom, b.geom)` | Extract only the shared portion |',
        '| Merge features | `ST_Union(geom)` | Dissolve boundaries for summary geometry |',
        '| Inspect plan | `EXPLAIN ANALYZE ...` | Confirm the planner uses GiST |',
        '| Pull into Python | `gpd.read_postgis(...)` | Turn SQL results into a GeoDataFrame |',
        '',
        '## 🛠️ Production habits to keep',
        '',
        '- Name geometry columns consistently and index them early.',
        '- Treat CRS metadata as part of data quality, not optional decoration.',
        '- Prefer explicit transforms in SQL so every teammate can see where units change.',
        '- Use `ST_DWithin` for candidate selection and `ST_Distance` only when you need ordered output.',
        '- Re-run `EXPLAIN ANALYZE` after each meaningful index or query rewrite.',
        '- Export only the final analytical result to Python when the database can do the heavy lifting first.',
        '',
        '## ⚠️ Common pitfalls to avoid',
        '',
        '- Measuring distance in EPSG:4326 degrees and reporting the number as if it were metres.',
        '- Buffering longitude/latitude geometries directly without a projected CRS step.',
        '- Assuming `ST_Distance < N` will behave like `ST_DWithin` for index usage.',
        '- Forgetting that overlay operations can return empty geometries that still need defensive handling.',
        '- Pulling millions of rows into Python when a single SQL predicate could reduce the result set first.',
        '- Reading a plan only for estimated cost and ignoring actual runtime and row counts.',
        '- Exporting data without checking whether the target format preserves CRS metadata correctly.',
        '- Mixing geometry and geography assumptions in the same workflow without documenting the choice.',
        '',
        '### ✅ Ready-for-production checklist',
        '',
        '- I can name the storage CRS and the analysis CRS used in my workflow.',
        '- I can explain which predicates are index-friendly and which ones are only for final measurement or display.',
        '- I know how to transform geometries before buffering, area, and nearest-feature analysis.',
        '- I can move confidently between SQL results, GeoDataFrames, and exported GeoJSON outputs.',
        '- I can justify when the database should do the heavy lifting and when Python should take over.',
        '- I can spot the difference between a teaching-safe approximation and a production-grade metric workflow.',
        '- I can explain each major query choice to a teammate reviewing my spatial analysis workflow.',
        '',
        '## 📖 Further Reading',
        '',
        '| Resource | Link |',
        '|----------|------|',
        '| PostGIS Reference | https://postgis.net/docs/reference.html |',
        '| ST_Intersects docs | https://postgis.net/docs/ST_Intersects.html |',
        '| ST_Buffer docs | https://postgis.net/docs/ST_Buffer.html |',
        '| Shapely manual | https://shapely.readthedocs.io/en/stable/manual.html |',
        '| PyProj CRS docs | https://pyproj4.github.io/pyproj/stable/ |',
        '',
        '---',
        '*Next: **Week 8 — Advanced Spatial Analytics** — nearest-neighbour, joins at scale, geometry repair, and performance tuning.*',
    ),
])

notebook = {
    'cells': C,
    'metadata': metadata,
    'nbformat': 4,
    'nbformat_minor': 5,
}

OUT.write_text(json.dumps(notebook, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
print(f'Wrote {OUT} with {len(C)} cells')
